### ISSUE TITLE
Avoid including python executables and libraries

### ISSUE THREAD

**Issue by msuchard** [OHDSI/PatientLevelPrediction#10]
I feel strongly that we should try to avoid distributing:
1. python executables, and
2. python libraries:mathplotlib, numpy, scipy, sklearn
inside our `R` package.

My motivation is that each time one of these dependencies changes, we will need an automatic system to update our package.  This is very hard to maintain.

Do not `PythonInR` or `RPython` work?  We can include a small function inside our package to test that python and its required libraries are installed.

**Comment by msuchard** [comment]
+1 for `PythonInR`

**Comment by PRijnbeek** [comment]
I fully agree we are testing the use of Anaconda on the windows platform now to install python and the use of PythonInR. to be continued

**Comment by PRijnbeek** [comment]
Jenna, you mentioned that this could only be done by Anaconda.

Why can’t we use this windows install of python exactly:

https://www.python.org/downloads/windows/

When I install this I am able to call python in R with PythonInR without problems:

pyConnect("C:/Python27/python.exe")
pyVersion()
[1] "2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]"

Am I missing something here?

**Comment by PRijnbeek** [comment]
Got it. Some of the libraries we need are only included in Anaconda. We will test Anaconda further tomorrow.

**Comment by PRijnbeek** [comment]
@jreps I tested the new code (without the DLLs etc) with a fresh install of Anaconda. R cannot find python yet though, we have to find out why.

**Comment by jreps** [comment]
Was it an issue with PythonInR::pyConnect(pythonExePath = NULL, dllDir = NULL, pythonHome = NULL)?  I was able to run that on windows and connect using a standard python install and anaconda without specifying pythonExePath but perhaps you need to specify it?  Have you tested the python using the command prompt to make sure it works?

**Comment by jreps** [comment]
So I just had a couple of minutes to check some things out and typing:
Sys.getenv('PATH') in R lets me see that on my laptop I have the anaconda location in my path and for the standard python install on my main computer I have C:/Python27 in my path, my guess is you are missing the python location from your path?  I'll add the details for adding the python location into the PATH within the installing python instructions so the users don't have to keep specifying it when they connect, I remember doing this for the standard python but I think anaconda actually did this for me automatically though?

**Comment by PRijnbeek** [comment]
Yes i checked that already of course, i can find Python without a problem in the cmd prompt so it seems to be in the path.

**Comment by jreps** [comment]
Do you get this error: "Error in autodetectPython(pythonExePath) : 
  Python could not be found please provide the path to "python.exe"
	(e.g. "C:\Python27\python.exe") or set the appropriate path variable!"?

If possible, can you restart R and then type Sys.getenv('PATH') to make sure the path is updated in the R session and then, if the python is in the path,  try PythonInR::pyConnect(pythonExePath = NULL, dllDir = NULL, pythonHome = NULL)?  If there is an error, can you please copy the message so I can see what is going wrong? Thanks

**Comment by PRijnbeek** [comment]
Yes that was the message I got.

Restarting R Studio seems to have solved the problem though. Looking at the path Anaconda is in the path and in that folder python.exe is present. In a windows cmd box it worked directly after the Anaconda install. Maybe R Studio is not getting the path when it searches for python but does this at the start. If we add the instruction to restart R Studio after the Anaconda install we will be fine.
