### ISSUE TITLE
Preference Plot in Shiny App is incorrect

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#100]
It shows a strange bar type representation. 

In Server version i replaced this using the plot function in the package. Now it is ok again.

We need to fix this in the Shiny App in the package as well.

It should be:

```
  output$prefPlotTest <- plotly::renderPlotly({
    if(is.null(reactVars$plpResult))
      return(NULL)
    print(
      ggplotly(plotPreferencePDF(reactVars$plpResult$performanceEvaluation,type='test'))
    )
  })
  output$prefPlotTrain <- plotly::renderPlotly({
    if(is.null(reactVars$plpResult))
      return(NULL)
    print(
      ggplotly(plotPreferencePDF(reactVars$plpResult$performanceEvaluation,type='train'))
    )
  })

```
See screen shot left is old right is fixed bug.

![screenshot 2018-10-06 20 11 35](https://user-images.githubusercontent.com/7252105/46574463-0d508380-c9a4-11e8-98e6-c66b60e33efd.png)

**Comment by PRijnbeek** [comment]
Fix in Shiny App branch

**Comment by jreps** [comment]
It might be worth having a chat about the shiny viewers.  We have the local single viewer, the local multiple viewer and then slightly different versions for the online single and multiple viewers.  Maybe we can just have the local single viewer in PLP and then the online multiple viewer will be in the plp skeleton?  We also need to merge the shiny app branch into master
