### ISSUE TITLE
RTools 3.5 and R 3.5.x issue

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#104]
Logging this for future reference.
---
Did a test on a clean system.

If you update all to latest version there are issues in installing packages through devtools.

It is a known issue not appropriately addressed yet by CRAN updates.

This workaround worked for me:
```
library(devtools)
assignInNamespace("version_info", c(devtools:::version_info, 
  list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), 
  "devtools")
find_rtools() # is TRUE now
```

See also this link:
https://github.com/r-lib/devtools/issues/1772

RTools 3.4 does not work with latest R! so probably best to stick to 3.4 for both R and RTools.

**Comment by t-abdul-basser** [comment]
Thanks @PRijnbeek!

**Comment by jreps** [comment]
Closing for now as hopefully new versions are being used :)
