### ISSUE TITLE
PythonInR causes R Session to crash

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/PatientLevelPrediction#105]
## Summary

I'm providing some information in the hopes that it might help others. @jreps and @PRijnbeek may have additional information on why I ran into this problem. 

While attempting to run the PatientLevelPrediction package, RStudio would suddenly crash my R session and never log any information. After troubleshooting this, I traced the problem down to the following command:

`PythonInR::pyConnect()`

Simply running this command would cause the entire R session to crash and require a new session start. For reference, I'm running Windows 10 (x64) and I'll detail all of my configuration later in this post. If you face the same issue, please read on.

## My Solution

The solution that worked for me was to install Python 3.6 directly versus using Anaconda. For reference, I had installed [Anaconda 5.3](https://www.anaconda.com/download/) which is bundled with Python 3.7. Per Anaconda's recommendation,  I used this version and then [configured it to use Python 3.6](http://docs.anaconda.com/anaconda/faq/#how-do-i-get-anaconda-with-python-3-5-or-3-6). I was able to verify that I was using Python 3.6 since I could run 'python' from the Windows command prompt and get a Python 3.6.6 prompt to appear.

After facing the session crash issue, I decided to uninstall Anaconda, rebooted Windows and then downloaded and installed Python 3.6 from [here](https://www.python.org/downloads/windows/). During the installation of Python 3.6, at the end of the install I also performed the recommended step of expanding the BASEPATH. I also confirmed that the following Python locations were added to my system PATH environment variable:

```
C:\Python\Python36\
C:\Python\Python36\Scripts\
```
_(Your paths may differ based on your installation choices)_

I then re-installed 'PythonInR' in my RStudio session (this might not be necessary but did it just in case). This then allowed the `PythonInR::pyConnect()` command to run with out issue. Then, I needed to run the following commands from a Windows command prompt to install dependencies necessary to run the PatientLevelPrediction package:

```
python.exe -m pip install --upgrade pip
pip3 install -U NumPy
pip3 install -U SciPy
pip3 install -U scikit-learn
pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.1-cp36-cp36m-win_amd64.whl
pip3 install torchvision
pip3 install --upgrade tensorflow
pip3 install keras
pip3 install -u importlib
```

Once I did this, just to be safe a did a forced installation of the PatientLevelPrediction package:

```
library(devtools)
install_github("OHDSI/PatientLevelPrediction", force=T)
```

Then I was able to run a full check of the package and verified that everything was working properly:

```
library(PatientLevelPrediction)
PatientLevelPrediction::checkPlpInstallation()
```

## Configuration

I'm running Windows 10 (x64) with the following:

- R for Windows 3.4.4
- RTools 3.4
- RStudio 1.1.456
- Python 3.6 as described above

I had attempted to use R 3.5.1 with RTools 3.5 but also faced some issues as described by @PRijnbeek in #104 so I decided to move back to R 3.4.4 which ultimately worked.  

Hope this helps if you face the same problems.

**Comment by jreps** [comment]
I've edited all the python functions to use reticulate instead of pythonInR in the efficient branch.  I'm doing some final tests and then I'll remove pythonInR versions and merge into master.  That should fix this problem.
