### ISSUE TITLE
python version issue

### ISSUE THREAD

**Issue by SungJun9212** [OHDSI/PatientLevelPrediction#106]
command  - 
model <- setLRTorch(autoencoder=autoencoder, vae=vae, class_weight=class_weight)

output - 
Initialize Python Version 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0]

Using the above command
python version 2.7 works..

I know I need to use version 3.6 of Python.

how to i solve?

**Comment by SungJun9212** [comment]
and 
I do not have python2.7

**Comment by jreps** [comment]
Are you using a Mac?  That has 2.7 as the default.  The code might still work with 2.7?

**Comment by SungJun9212** [comment]
To jreps.

thank. jreps.
im using a linux, ubuntu 18.04 LTS .

I have encountered the following error: 
No module named numpy
Error in value[[3L]](cond) :
  Error in pyExec(sprintf("import %s as %s", import, as)): An error has occured while executing Python code. See traceback above.

so i thought that 'python version',

and numpy package's installed in python3.

**Comment by jreps** [comment]
if you have python3 you can use pip to install python.  Go to a terminal and try (you might need to add your python version number after python e.g., python3 ...):
python -m pip install numpy

If you don't have pip (this link might help https://linuxize.com/post/how-to-install-pip-on-ubuntu-18.04/ )

**Comment by SungJun9212** [comment]
I was confused the version.
it was solved because of you.
thank you for your comment, jreps  :)

**Comment by jreps** [comment]
Glad to hear it is solved, I'll now close this issue.  If you have any other issues please let us know.
