### ISSUE TITLE
temporal data support for age/gender

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#108]
The conversion from plpData to sparse tensor for temporal data doesn't work for variables that do not have a timeId.  It would be good to have variables such as gender constant for each time point and age changing.  A simple way to convert age could be to multiple the age in years by 365 and then add the timeStart (to get the approx age in days at the start of each time period).

**Comment by chandryou** [comment]
Yes, I totally agree with @jreps 's opinion :)

**Comment by jreps** [comment]
I've now added this into the efficient branch for testing - toSparseM() in the efficient branch should now add in the covariates that have an timeId of 0 using the logic stated above.
