### ISSUE TITLE
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck =vI[[i]]) :

### ISSUE THREAD

**Issue by jepark315** [OHDSI/PatientLevelPrediction#114]
I'm trying to install this package with different versions but this same error pops up. What is the problem going on?

**Comment by jepark315** [comment]
Sure! I'm sorry those picutres look terrible but this is my best for now..
Please tell me if there's any info needed to make it work.
 
![kakaotalk_20190201_160242656](https://user-images.githubusercontent.com/43940996/52107765-fdd40500-263a-11e9-9e71-768eb315c37f.jpg)
![kakaotalk_20190201_160244221](https://user-images.githubusercontent.com/43940996/52107771-00cef580-263b-11e9-94db-828e062d9f1d.jpg)

**Comment by schuemie** [comment]
Well, the error message suggests you're missing some dependency, but for some reason the characters of the error message are not showing properly (probably something to do with the Korean character set).

Are you using drat or devtools to install PatientLevelPrediction?

Also, could you tell me what version of devtools you're running:

```r
packageVersion("devtools")
```

**Comment by jepark315** [comment]
I didn't use drat or devtools.(I'm not able to use any of those..) I just downloaded files and moved to the server. I think version of dependency is causing the error but have no idea how I could figure it out.

**Comment by jreps** [comment]
do you still have the issue with the latest code in master?

**Comment by jepark315** [comment]
> do you still have the issue with the latest code in master?

Yes, I couldn't fix it. Any comment would be so much helpful :)

**Comment by chandryou** [comment]
@jreps, it is possible to install PLP package without Python?

**Comment by jreps** [comment]
It should install without python, but the python functions will not work, only lasso logistic regression, knn and gradient boosting.  @jepark315, did you try with the latest code committed 5 hours ago?  I think I had some issue similar to yours at some point over the past few days but it was fixed in the latest commit.  Do you have all the dependancies listed in the package installed (these are found in the description file)?

**Comment by jepark315** [comment]
@jreps Thanks to you, I checked the dependancies again and solved this issue so simply. Thank you very much for your comment :)
