### ISSUE TITLE
Move some dependencies to Suggests, install as needed?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#117]
PatientLevelPrediction has [an impressive list of dependencies in the Imports section](https://github.com/OHDSI/PatientLevelPrediction/blob/master/DESCRIPTION#L24), which may make installation more difficult.

Perhaps some could be moved to the Suggests section instead, and be installed as needed? An example is [this pattern used in SqlRender](https://github.com/OHDSI/SqlRender/blob/master/R/ShinyApps.R#L27), where Shiny is only installed when you're launching the Shiny app.

Some candidate dependencies:
- BigKnn
- shiny
- plotly
- DT
- htmlwidgets
- OhdsiSharing

**Comment by jreps** [comment]
I've been working on the efficient branch and will be aiming to merge this into master soon.  In that branch (based on your previous post) I've moved BigKnn and some other dependancies.  OhdsiSharing wasn't used so I removed that.  I'll look into also making the shiny viewer related libraries also optional.

**Comment by jreps** [comment]
I've done this in efficient and plan to merge efficient into master soon.
