### ISSUE TITLE
Docker image for PLP package

### ISSUE THREAD

**Issue by chandryou** [OHDSI/PatientLevelPrediction#118]
I've created docker image for PLP package, version 3.0.0 with tensorflow, keras, and torch (https://github.com/ABMI/ohdsi-docker).

You can run docker image as described below

`docker run -e USER=user -e PASSWORD=password1 -d -p 8787:8787 chandryou/patientlevelprediction_cpu`

Then you can open the rstudio in the web browser

`http://localhost:8787`

Still, an error keeps occurred whenever the function uses 'OhdsiRTools'. I think there is conflict between ohdsiRTools and ParallelLogger in ohdsi R ecosystem. 

`Error: evaluation nested too deeply: infinite recursion / options(expressions=)?` 

I don't know how to fix this. 
Do you have any idea for this? @jreps  @schuemie @PRijnbeek @msuchard

**Comment by jreps** [comment]
This should be fixed in master and efficient now :)
