### ISSUE TITLE
confusing error message in data splitter

### ISSUE THREAD

**Issue by chandryou** [OHDSI/PatientLevelPrediction#119]
In personSplitter function in 'DataSplitting.R', at the line 64, the error message seems confusing. 

```
  if (length(table(population$outcomeCount)) <= 1 | sum(population$outcomeCount > 0) < 10) {
    stop("nfold must be an integer 1 or greater")
  }
```
I think the error message should be something like: 'Each number of population with and without outcome should be 10 or more'

I concern that I can make a conflict if I make a PR, because @jreps is working on efficient branch, now.

**Comment by jreps** [comment]
I edited the message, thanks for letting me know about it :)
