### ISSUE TITLE
Quick Install Guide Feedback

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/PatientLevelPrediction#128]
### Background

I'm following the Quick Install Guide: https://ohdsi.github.io/PatientLevelPrediction/articles/PatientLevelPrediction.html an attempting to set up the Patient Level Prediction package and ran into a few small items that I wanted to note. I'm happy to create a pull request with some of the edits suggested below but before going ahead, I wanted to confirm that the suggestions below are worthwhile.

#### Environment

My target environment is a Windows Server 2012 R2 virtual server. I have installed R v3.4.4, RTools v3.4.0.1962 and RStudio v1.0.153 as my base configuration.

#### Installing the R package

I was able to install all of the R packages without issue. 

#### Setting up Python

I was also able to install Anaconda with the default options selected. However, I did run into an issue when running:

```
system("python --version") 
```

This was quickly remedied by adding the Anaconda installation location (for me this is `D:\Anaconda3`) to my PATH as described in the setup guide. I'd suggest to expand this a bit though since I did need to make some additional edits to my system PATH variable when installing Keras. Here is the list of Anaconda related PATH entries I added to get the Keras install problems remedied:

```
D:\Anaconda3;D:\Anaconda3\Scripts;D:\Anaconda3\Library\bin
```

(more on the Keras setup issues shortly).

#### Testing the PatientLevelPrediction Installation

When attempting to run the following code:
```
> library(DatabaseConnector)
> connectionDetails <- createConnectionDetails(dbms = "<hidden>",
+                                              connectionString = "<hidden>",
+                                              user = "<hidden>",
+                                              password = "<hidden>")
> PatientLevelPrediction::checkPlpInstallation(connectionDetails = connectionDetails, 
+                                              python = T)
```
I got the following output
```
Checking database connectivity
Connecting using <hidden> driver
- Done

Checking R population
Generating covariates
Error in simulatePlpData(plpDataSimulationProfile, n = sampleSize) : 
  object 'plpDataSimulationProfile' not found
In addition: Warning message:
In data(plpDataSimulationProfile) :
  data set ‘plpDataSimulationProfile’ not found
```

The edit required here is to make sure you call "library(PatientLevelPrediction)" prior to calling the code above which will load the ~/data/plpDataSimulationProfile.rda included in the PLP R package.

#### Installing Keras

Per the guide, I attempted to run this:

```
devtools::install_github("rstudio/keras")
library(keras)
install_keras()
```
The installation of "rstudio/keras" completed and when the library was loaded, I got the followng:

```
> library(keras)
Error: package or namespace load failed for ‘keras’:
 .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'tensorflow'
```

I restarted my R Session and re-attempted to load up the keras library and then it worked without issue. I then attempted to run the `install_keras()` command **BEFORE** adding the additional Anaconda paths to my system PATH environment variable and got the following error:

```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))
```

Once I added the additional folders (`D:\Anaconda3\Scripts;D:\Anaconda3\Library\bin`) to my system PATH environment variable, the install worked properly.

#### Creating A PLP Python Vitual Environment

This all worked well!

**Comment by jreps** [comment]
I've updated based on your edits, thanks :D
