### ISSUE TITLE
Merge of logging functionality

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#13]
HI Jenna,

I have pushed the merge. Some open action points:
- [x] We need to have a look at the new Save option. I am not sure this will work correctly yet. For example with the python models you need to have directory to save the libsvm to if this is done on the fly. Also the log file needs to end up somewhere. Some tests need to be done on this still I think.
- [x] We need to decide on the number of logging levels we will use/want and their names. We could also use SILENT as level instead of FATAL and NORMAL instead of INFO etc. We could also use the integers 1-5 etc. It can be as simple or advanced as we want and think is needed. 
- [x] We need to clean up the logging message created by each model some are a bit too verbose now. I just added all that was there.
- [x] I saw testhat now creates libsvm folder under tests for one of your tests. We need to clean this.
- [x] I fixed all the Travis errors, there are some messages left for your to fix mainly related to documentation. Note that travis functionality is degraded tonight, they appear to have some problems. This is probably why the travis job is still running while it ended successfully. The logger branch is green.

Let's have a chat tomorrow.

Peter

**Comment by jreps** [comment]
Great, I've added a line to remove the libsvm file when testing and will sort out any travis messages this afternoon.  With the save, it just replaces the dirPath in the previous version, for large-scale analysis saving all the models will take too much space so I thought we need to be able to disable saving the models automatically (maybe we just need levels of saving, 0=nothing, 1=logging/performance, 2=logging/performance/model).  For the libsvm on the fly, can we use some temp location?
