### ISSUE TITLE
createResultsDoc fails from Atlas generated skeleton

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/PatientLevelPrediction#133]
**Describe the bug**
I've downloaded a PLP R package I've designed in ATLAS. While attempting to use the `createResultsDoc` option of the main `execute` function, I get the following error:

```
Error in DOCX_(file, bg, width, height, pointsize = pointsize, aliases = list(system = system_fonts,  : 
  Graphics API version mismatch
```

**Set up (please run in R "sessionInfo()" and copy the output here):**

> > sessionInfo()
> R version 3.4.4 (2018-03-15)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows Server >= 2012 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] MyStudyPackage_0.0.1       DatabaseConnector_2.4.0
> 
> loaded via a namespace (and not attached):
>  [1] tidyselect_0.2.5             ffbase_0.12.7                reshape2_1.4.3              
>  [4] purrr_0.3.2                  splines_3.4.4                rJava_0.9-11                
>  [7] lattice_0.20-35              colorspace_1.4-1             htmltools_0.3.6             
> [10] viridisLite_0.3.0            base64enc_0.1-3              survival_2.41-3             
> [13] plotly_4.9.0                 rlang_0.3.4                  pillar_1.3.1                
> [16] glue_1.3.1                   DBI_1.0.0                    gdtools_0.1.6               
> [19] ParallelLogger_1.1.0         xgboost_0.82.1               Cyclops_2.0.2               
> [22] uuid_0.1-2                   foreach_1.4.4                plyr_1.8.4                  
> [25] stringr_1.4.0                munsell_0.5.0                gtable_0.3.0                
> [28] zip_2.0.1                    htmlwidgets_1.3              codetools_0.2-15            
> [31] labeling_0.3                 ff_2.2-14                    Rcpp_1.0.1                  
> [34] scales_1.0.0                 jsonlite_1.6                 bit_1.1-14                  
> [37] fastmatch_1.1-0              ggplot2_3.1.1                digest_0.6.18               
> [40] stringi_1.4.3                dplyr_0.8.0.1                SqlRender_1.6.1             
> [43] grid_3.4.4                   tools_3.4.4                  magrittr_1.5                
> [46] lazyeval_0.2.2               FeatureExtraction_2.2.2      tibble_2.1.1                
> [49] crayon_1.3.4                 tidyr_0.8.3                  pkgconfig_2.0.2             
> [52] MASS_7.3-49                  Matrix_1.2-12                data.table_1.12.2           
> [55] xml2_1.2.0                   rvg_0.1.5                    assertthat_0.2.1            
> [58] officer_0.3.3                httr_1.4.0                   rstudioapi_0.10             
> [61] iterators_1.0.10             R6_2.4.0                     PatientLevelPrediction_3.0.3
> [64] compiler_3.4.4 
> 

**Fix**
I was able to fix this problem by updating to rvg_0.2.0 from rvg_0.1.5 by running: install.packages("rvg"). Once I did that and re-ran the `createResultsDoc`, I only received warnings:

```
Warning: dml_docx() is deprecated and will be removed in the next version (> 0.2.0), use devEMF::emf instead.
Warning: Removed 32 rows containing missing values (geom_path).
Warning: dml_docx() is deprecated and will be removed in the next version (> 0.2.0), use devEMF::emf instead.
Warning: Removed 32 rows containing missing values (geom_path).
Warning: dml_docx() is deprecated and will be removed in the next version (> 0.2.0), use devEMF::emf instead.
Warning: Removed 32 rows containing missing values (geom_path).
Note: zip::zip() is deprecated, please use zip::zipr() instead
```

Making a note of this here since I'm not sure where the rvg package lives in the dependency chain in PLP.

**Comment by jreps** [comment]
This has now been removed.  The Skeleton package contains markdown for creating the protocol and may be updated to create a result document in the future.
