### ISSUE TITLE
Updates for encoders

### ISSUE THREAD

**Issue by chandryou** [OHDSI/PatientLevelPrediction#134]
**Is your feature request related to a problem? Please describe.**
For temporal analyses, I want more encoder options to improve predictive power. 

**Describe the solution you'd like**
I'll try to add 1-D convolutional autoencoder, 1D-convolutional VAE, and VQ-VAE.

**Additional context**
For convoluational autoencoder:
https://github.com/chandryou/selfstudy/blob/master/dimensionReduction/convolutional_autonecoder.r

For convolutoinal VAE:
https://github.com/chandryou/selfstudy/blob/master/dimensionReduction/convolutionalVAE.r

For VA-VQE: 
https://keras.rstudio.com/articles/examples/vq_vae.html

**Comment by jreps** [comment]
closing this as deep learning is now in DeepPatientLevelPrediction
