### ISSUE TITLE
Errors while using temporal data

### ISSUE THREAD

**Issue by chandryou** [OHDSI/PatientLevelPrediction#135]
**Describe the bug**
toSparseM function in 'Formatting.r' often returns errors when using temporal data. 

I think this is caused while adding non-temporal features to the temporal features. 
Currently, it seems that age and another non-temporal feature should be included in the temporal feature setting. Otherwise, it makes errors. 

Current my solution is just passing this when there is no non-temporal features in the feature setting.
Please see this [commit](https://github.com/ABMI/PatientLevelPrediction/commit/0960f15a1a5761e24fc8d8e50e57d23aa0810a94)

@jreps I don't think this is the best solution. Could you suggest a better one?

**Comment by jreps** [comment]
Hi Chan, thanks for letting me know about this.  I'll take a look tomorrow, I also need to fix the covariateSummary for temporal data so will try and get those both solved asap.

**Comment by jreps** [comment]
I've added the ability to add non-temporal features into the temporal data object
