### ISSUE TITLE
Docker image support

### ISSUE THREAD

**Issue by p-shen** [OHDSI/PatientLevelPrediction#136]
I am having issues installing PLP on AWS SageMaker due to limitations of how the environments can can be configured. The docs provided with the installation works great for a single environment configuration, but doesn't work great for scaling to multiple machines.

I see that another user has created Docker images for PLP (https://github.com/ABMI/ohdsi-docker), but I am wary of how well that will be supported in the future.

Would the OHDSI team be able to have an officially supported Docker image?

**Comment by chandryou** [comment]
@p-shen 
We're discussing about official support of OHDSI docker images with @leeevans 

While I'm doing OHDSI, I'll support OHDSI docker images as long as I can. 

If you have any question about the OHDSI docker image for PLP (https://github.com/ABMI/ohdsi-docker), please let me know.
