### ISSUE TITLE
Multiple PLP viewer doesn't support analyses with covariateSettings represented by list

### ISSUE THREAD

**Issue by pavgra** [OHDSI/PatientLevelPrediction#141]
**Issue description**

[FeatureExtraction](https://github.com/OHDSI/FeatureExtraction) package (and specifically `getDbCovariateData` method) supports two formats for `covariateSettings` parameter. One is *covariateSettings* `class`. Another, default type, is `list`:

https://github.com/OHDSI/FeatureExtraction/blob/master/R/GetCovariates.R#L112:
```
if (class(covariateSettings) == "covariateSettings") {
  covariateSettings <- list(covariateSettings)
}
if (is.list(covariateSettings)) {
  covariateData <- NULL
  hasData <- function(data) {
    return(!is.null(data) && nrow(data) != 0) 
  }
  for (i in 1:length(covariateSettings)) {
    fun <- attr(covariateSettings[[i]], "fun")
```

Official example of `covariateSettings` passed as `list`:
https://raw.githubusercontent.com/OHDSI/FeatureExtraction/master/inst/doc/CreatingCustomCovariateBuilders.pdf
![image](https://user-images.githubusercontent.com/10010071/60295862-c2401d00-98f2-11e9-8c44-9d0fe42bf006.png)

So, it is valid to pass `covariateSettings` parameter represented by `list` data type. However, when you try to execute `PatientLevelPrediction::viewMultiplePlp` it extracts covariates assuming that the covariateSettings parameter is represented by the `class` data type only:

https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/ViewMultiplePlp.R#L324
```
covariates <- eval$model$metaData$call$covariateSettings
population <- eval$model$populationSettings
covariates <- data.frame(covariateName = names(covariates), 
```

The `names(covariates)` execution over a variable having type `list` doesn't make sense:
![image](https://user-images.githubusercontent.com/10010071/60296082-4f837180-98f3-11e9-82ea-182c5f44d0e0.png)

**Proposal**
- Simple - repeat logic presented in FeatureExtraction: expect covariateSettings to be `list` (and work with it as a list) and if the parameter is `class` - wrap it into a list.
- Advanced - add `map`/`forEach` method into `FeatureExtraction` package which would allow to iterate over covariateSettings and encapsulate the data types resolution logic inside the FE package (tagging @schuemie here)

**Comment by jreps** [comment]
fixed
