### ISSUE TITLE
Support name extraction from custom covariate

### ISSUE THREAD

**Issue by pavgra** [OHDSI/PatientLevelPrediction#142]
If you follow the manual for custom covariate definition presented in [FE repo](https://raw.githubusercontent.com/OHDSI/FeatureExtraction/master/inst/doc/CreatingCustomCovariateBuilders.pdf) and supply such custom covariate into `PatientLevelPrediction::viewMultiplePlp`, it's name won't be extracted since the code used for name extraction is:

https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/ViewMultiplePlp.R#L326)
```
covariateName = names(covariates)
````

**Comment by jreps** [comment]
fixed
