### ISSUE TITLE
CDM V 6.0 support

### ISSUE THREAD

**Issue by jkylearmstrong** [OHDSI/PatientLevelPrediction#148]
Requesting support for CDM V 6.0

**Comment by jreps** [comment]
Hi, I just edited Feature extraction to be compatible with v6: https://github.com/OHDSI/FeatureExtraction/tree/cdm_v6 - if you install FE from this branch you should be able to run PLP with v6.0 by putting cdmVersion = '6' in the function getPlpData() 

I'm going to check whether the prediction skeleton package needs minor edits to make it fully support v6 now.

**Comment by jreps** [comment]
I noticed there are some bits in PLP I need to update for v6 but they probably won't cause any issues.  I'll close this once I edit PLP to make it fully compatible.
