### ISSUE TITLE
Spark Support

### ISSUE THREAD

**Issue by jkylearmstrong** [OHDSI/PatientLevelPrediction#149]
Request to add spark support.

**Comment by jreps** [comment]
Hi,

I tested integrating Spark a couple of years ago and found that the overhead to set up the parallelization wasn't worth it with the data size I was using.  Do you currently find the runPLP to be slow?  I can probably find the old code and add it back if you are have having performance issues.

Best wishes,
Jenna

**Comment by egillax** [comment]
I don't think we will add this. We are anyway using Andromeda objects for most of our operations so this issue probably belongs there. Anyway spark is not really close to being the most performant when you are dealing with data that fits on one machine. See for example this: https://duckdblabs.github.io/db-benchmark/
