### ISSUE TITLE
Auto-optimization vs grid searches

### ISSUE THREAD

**Issue by msuchard** [OHDSI/PatientLevelPrediction#15]
@jreps Here are some pointers to some alternatives to grid searches:
- [HParSearch.h](https://github.com/OHDSI/Cyclops/blob/master/src/utils/HParSearch.h)  -- Main code
- [Use case](https://github.com/OHDSI/Cyclops/blob/master/src/cyclops/drivers/AutoSearchCrossValidationDriver.cpp#L101)

**Comment by egillax** [comment]
I'm closing this. Thanks for the links to the code. We are exploring other alternatives to grid search in other issues that will be kept open.
