### ISSUE TITLE
Installation guide: improving documentation on package dependencies

### ISSUE THREAD

**Issue by kmkostka** [OHDSI/PatientLevelPrediction#150]
The PLP skeleton contains a DESCRIPTION file that lists packages to execute a PLP study. The current PLP installation guide has an Installation Issues section explaining how to install a dependency if R notes it needed to be installed but does not include this list of packages. There's really not anywhere that helps someone find all of the CRAN dependencies for the PLP library besides this DESCRIPTION file.

It would be more user-friendly to include the same level of detail from the DESCRIPTION file in the guide so users can quickly run a few installs versus having to keep looking for dependency error messages.

**Comment by jreps** [comment]
Hi Kristin, Martijn added a function for automatically installing packages that I copied over to PLP.  I'll have a look at the packages that are in the skeleton but not in PLP and create a function for automatically installing them if missing.  I'll add this to the skeleton extras folder and add instructions to make this simple to run.  Hopefully that will make things nicer :)

**Comment by jreps** [comment]
Hi Kristin,

I've initially updated the Skeleton prediction package (I added a script that will install any missing dependancies and improved the readme, including adding info about running the dependency install script).  Here is the latest skeleton: https://github.com/OHDSI/StudyProtocolSandbox/tree/master/SkeletonPredictionStudy

If you have any feedback about the instructions that would be great.  I want it to be easy to share the models and add the validation results but I'm not sure whether the readme is fully there yet!
