### ISSUE TITLE
Images missing from vignette

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/PatientLevelPrediction#151]
**Describe the bug**
Two images missing from the [Building Predictive Models vignette](https://ohdsi.github.io/PatientLevelPrediction/articles/BuildingPredictiveModels.html) under example 1: study implementation. It looks like they are supposed to be ATLAS specifications of cohorts.

**Comment by jreps** [comment]
Oh, I think this is something to do with the way we are referencing it that the website doesn't like. I'll take a look at fixing this.
