### ISSUE TITLE
add permutation feature importance

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#155]
**Is your feature request related to a problem? Please describe.**
The variable importance measures in the package are different for each method.  It would be nice to have a consistent measure.

**Describe the solution you'd like**
Use permutation feature importance (https://christophm.github.io/interpretable-ml-book/feature-importance.html) for each classifier

**Comment by jreps** [comment]
initial code has been added to the 'development' branch

**Comment by sanyabt** [comment]
Hi @jreps, is this same as the permutation feature importance used by the scikit-learn package here - [sklearn.inspection.permutation_importance](https://scikit-learn.org/stable/modules/generated/sklearn.inspection.permutation_importance.html#sklearn.inspection.permutation_importance)? I'd like to get the permutation importance for my random forest model using PLP data.
