### ISSUE TITLE
Add clear guidelines to run the analysis R-package that we get from Atlas

### ISSUE THREAD

**Issue by SulevR** [OHDSI/PatientLevelPrediction#158]
When you download an analysis R-package from Atlas, one follows the installation guidelines from [the book of OHDSI](https://ohdsi.github.io/TheBookOfOhdsi/PatientLevelPrediction.html):

_Once you have opened the project in R Studio, you can open the README file, and follow the instructions. Make sure to change all file paths to existing paths on your system._

However, I suggest the following modifications in the readme file of the package:

1. Consider renaming "Instructions To Prepare Package Outside Atlas" as it is not clear whether you should follow these steps in R after dowloading the package from Atlas (it is outside Atlas). Perhaps it would be better to rename it to "Instructions To Prepare Package without Atlas" or even "Instructions To Prepare Package without Atlas (skip it when you prepared your package in Atlas)"

2. In "Instructions To Run Package" instead of long story, just say that open CodeToRun.R, replace the database credentials, select the analyses to run and run the whole script. Currently, it starts with the instructions to add it to github etc, which is not the thing that you want to make first.

**Comment by jreps** [comment]
This has been revised in the latest prediction skeleton - ATLAS needs to be updated to use the latest skeleton so it has the updated readme.
