### ISSUE TITLE
Covariate setting name in Shiny results table

### ISSUE THREAD

**Issue by CHUNGGAK** [OHDSI/PatientLevelPrediction#159]
I can sort multiple analyses by database name, model name and target, outcome name in Shiny.
But I can't do it by covariate setting name.
I should click a model and click covariate settings button.

If I can set a covariate name and the covariate name column is added to the results table, it will be very convenient.

Thank you.

**Comment by jreps** [comment]
Added in this version of the app: https://data.ohdsi.org/Covid19ValidatingCovVulIndex/ - I'll pull this version into the master PLP soon
