### ISSUE TITLE
Inconsistent number of outcome events in plp_document.docx

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/PatientLevelPrediction#172]
**Describe the bug**
The number of outcomes is inconsistent in the plp_document.docx generated by the PLP packages.

**Set up (please run in R "sessionInfo()" and copy the output here):**
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**To Reproduce**
Run this prediction package https://epi.jnj.com/atlas/#/prediction/181.

**PLP Log File**
[log.txt](https://github.com/OHDSI/PatientLevelPrediction/files/4752838/log.txt)

**Additional context**
Inconsistency in the plp_document.docx marked with red circle:
<img width="583" alt="outcomes" src="https://user-images.githubusercontent.com/7384198/84162945-3d053800-aa71-11ea-8b4f-2179a650a6a7.png">

**Comment by jreps** [comment]
This should have been fixed with the updated createStudyPop and attrition
