### ISSUE TITLE
Probably typo in Fit.R

### ISSUE THREAD

**Issue by rekkasA** [OHDSI/PatientLevelPrediction#173]
In Fit.R (line 92) plpData$CovariateData should be plpData$covariateData (c shouldn't be capitalized). This causes sometimes issues with normalization when applying the model.

After fixing this, I got errors in applyTidyCovariateData function (line 106). The following may fix the problem:
	- line 121: Drop the rename part.
	- line 126: Replace maxs with maxValue

**Comment by jreps** [comment]
Thanks for spotting this!  I've updated and will commit the fix once the tests complete.
