### ISSUE TITLE
Installing PLP 4.0.5

### ISSUE THREAD

**Issue by ted9219** [OHDSI/PatientLevelPrediction#180]
**Describe the bug**
Hi, When I install the patient level prediction version 4.0.5, I got some error like below:

Error : (converted from warning) unable to re-encode 'EvaluatePlp.R' lines 110, 112
ERROR: unable to collate and parse R files for package 'PatientLevelPrediction'

EvaluatePlp.R 
```R
line 110 ParallelLogger::logTrace('Calculating Hosmer–Lemeshow Calibration Line')
line 112 ParallelLogger::logInfo(sprintf('%-20s%.2f%-20s%.2f', 'Hosmer–Lemeshow calibration gradient: ', calLine10$lm[2], ' intercept: ',calLine10$lm[1]))
```
name encoding problems?

**Set up (please run in R "sessionInfo()" and copy the output here):**
PatientLevelPrediction v4.0.5

**Additional context**

**Comment by ted9219** [comment]
PatientLevelPrediction 4.0.2 is installed normally.

**Comment by jreps** [comment]
I just tested on my Mac and 4.0.5 installs.  The only thing I can think is that the '-' in 'Hosmer–Lemeshow' is causing issues - but it is odd that it isn't complaining about it in the lines above.  I'll edit the '-' now and then see whether that fixes it?

**Comment by jreps** [comment]
I've retyped '-' on lines 110/112 - see whether that works?

**Comment by ted9219** [comment]
When I got this error, I installed it on the window. 
Now, the error is resolved. Thanks
