### ISSUE TITLE
Feature Request: Setting a seed for sampling a cohort for creating reproducible samples

### ISSUE THREAD

**Issue by tomseinen** [OHDSI/PatientLevelPrediction#192]
**Is your feature request related to a problem? Please describe.**
Currently, it is AFAIK not possible to compare two (or more) covariate settings using the same cohort sample using the getPlpData function.
Running the `getPlpData(connectionDetails,...,sampleSize=10000,covariateSettings)` function will always result in a new random sample of size 10000 of the cohort. Thus, running getPlpData twice with different covariateSettings will not use the exact same sample.

**Describe the solution you'd like**
I think it would be nice to be able to set a seed in the getPlpData function:
`getPlpData(connectionDetails,...,sampleSize, sampleSeed, covariateSettings)`

Similar to setting a seed for splitting data into test and training sets:
`runPlp(...,splitSeed,...)`

**Describe alternatives you've considered**
A workaround is sampling the cohort yourself and storing the result as a new cohort. This new cohort can then be used for the plpData creation without the need of sampling.

**Additional context**
I tried to understand how the SQL based random sampling works in the CreateCohorts.sql. But I can't figure it out, primarily because I don't see how the randomness is created.
Using the RAND() SQL server function could solve the problem as that function can be given a seed: RAND(42), or the RANDOM() postgres function with setseed().
Or perhaps a seed could be incorporated in the current sampling technique.

Do other people also think this is an interesting feature? Is this possible? Or is there may be a specific reason why this has not been implemented?

Thank you!
Tom

**Comment by jreps** [comment]
fixed in the main branch now
