### ISSUE TITLE
trainDeepNN size mismatch during call to keras::predict_proba

### ISSUE THREAD

**Issue by dapritchard** [OHDSI/PatientLevelPrediction#194]
**Describe the bug**

I'm working on a project using PatientLevelPrediction v3.0.5. When evaluating a call to `runPlp` using an object created by a call to `setDeepNN` as the input to the `modelSettings` parameter, I was getting errors of the following form.
```
Error in py_call_impl(callable, dots$args, dots$keywords): ValueError: Error when checking input: expected dense_input to have shape (74,) but got array with shape (1,)
```
The error would occur at the line <https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/DeepNN.R#L272> during the last iteration of the for loop. After inspecting the loop, I realized that the size of the data had by chance resulted in the last element of `batches` being a length-1 vector. It is my belief that when indexing by `[batch,]` with a length-1 value for `batch` this was returning a vector instead of a matrix which was causing problems. By changing that part of the code to `[batch,,drop=FALSE]` (and performing a similar change later in the `trainDeepNN` function), I was seemingly able to prevent the error from occurring.

**Set up (please run in R "sessionInfo()" and copy the output here):**

    R version 3.5.3 (2019-03-11)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Amazon Linux AMI 2018.03

    Matrix products: default
    BLAS: /mnt/r-stuff/R-latest/R-3.5.3/lib/libRblas.so
    LAPACK: /mnt/r-stuff/R-latest/R-3.5.3/lib/libRlapack.so

**Aside: PatientLevelPrediction package version**

As a total aside, the reason that I'm using an older version of PatientLevelPrediction is because this was the default value suggested for me when filling out the corresponding field in the Cloudformation template provided by the OHDSI on AWS. If it is recommended that people use newer versions of PatientLevelPrediction, then perhaps the defaults provided by OHDSI on AWS could be updated accordingly.

**Comment by jreps** [comment]
Thanks :) I made this edit as suggested.  

I would recommend using the latest PatientLevelPrediction as it will be new features.  The AWS defaults should be updated as v3.0.5 is outdated - I need to figure out where they are being set.
