### ISSUE TITLE
reproducibility issue with data split

### ISSUE THREAD

**Issue by rossdwilliams** [OHDSI/PatientLevelPrediction#195]
**Describe the bug**
When using the same split size and seed, running twice on the same plpdata/population produced two different splits in the data

I retrained a model and recreated the plpdata/population objects to do that and then when the data was split into person train/test this didnt match the original 

**Set up (please run in R "sessionInfo()" and copy the output here):**
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by jreps** [comment]
Did you use the same population?  I can't repeat this.  Can you provide example code.

If you sample when extracting plpData you can get a different sample of patients (even with the same settings) and this could cause an issue in the splits if you then create two populations from different plpData objects. If you use the same population the split will be the same.

**Comment by rossdwilliams** [comment]
I was using the atlas generated package to run the analysis and I did sample. I had a problem with my python installation so the random forest model failed, but Lasso and GBM worked. When I reran (only the RF models) after fixing the python I then got the different split, but i guess thats because i was using a sample of the plpdata.

I can send you the package if thats helpful but it was just the standard one generated from atlas

**Comment by jreps** [comment]
yeah - the sample is the reason.  If you sample you end up with a different plpData object and therefore different populations so the split seed doesn't make sense as you have different inputs.  If you sample you need to use the same plpData if you want the same results.

**Comment by jreps** [comment]
Closing this as the issue will be resolved if we can add a seed to the sample (or figure out a way to sampled consistently)
