### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by annamarianau** [OHDSI/PatientLevelPrediction#198]
Hello, 

I wanted to ask if the current PatientLevelPrediction package or maybe another package supports predicting the next value or values using temporal data? Thank you!

-Anna

**Comment by jreps** [comment]
Currently the package only supports binary classification or time-to-event analysis.  However, if you were interested in regression, then the framework is flexible and you could plug a regression method in.  Suitable metrics to evaluate the regression models would also need to be added to the package.  So, to summarize, at the moment it does not support predicting next value, but it could if people want to add that code.

**Comment by annamarianau** [comment]
Sounds good, thank you for your help!
