### ISSUE TITLE
Trailing semi-colon triggers Oracle error in when running via Oracle DBMS

### ISSUE THREAD

**Issue by eric-chou** [OHDSI/PatientLevelPrediction#20]
Hello, when running the getPlpData in R with Oracle DBMS, the file under the path (PatientLevelPrediction/inst/sql/sql_server/GetCohorts.sql) seems bring about an error (ORA-00911: invalid character) that causes this R command to 

Locally, we worked this out by going into GetCohorts.sql and editing to remove the trailing semicolon in the final line (line 15), so that the file ends with "ORDER BY subject_id" instead of "ORDER BY subject_id;" this error no longer occurs.

**Comment by chrisknoll** [comment]
Semicolins are used in SQL render to divide line spaces. The sql gets split on ';' before executing so if you are taking SQL out of the OHDSI tool and dropping it right into your sql CLI, it won't work, you'll have to remove the ; directly.

If you are seeing this error when executing the commands within the OHDSI tools, then the sql isn't being split properly before execution.

**Comment by schuemie** [comment]
My bad. @chrisknoll : when calling `querySql` or `querySql.ffdf`, in other words when performing single queries that return a result set, no splitting is done, and no semicolons are removed. I'll remove the semicolon from the SQL file, and maybe in [SqlRender version 2.0](https://github.com/OHDSI/SqlRender/milestone/1) we can introduce a more systematic fix to this problem.
