### ISSUE TITLE
getDbPlpData is gone

### ISSUE THREAD

**Issue by aaalgo** [OHDSI/PatientLevelPrediction#200]
**Describe the bug**

The function getDbPlpData exists in document but is gone from the code.  Is there a replacement function?

**Comment by jreps** [comment]
Hi, the function getPlpData() can be used to extract the data.  What document was using getDbPlpData?  That typo needs to be fixed as the function has been getPlpData() for a few years.

**Comment by aaalgo** [comment]
Thanks, it makes sense now.   Grepping the files under `man` gives me three entries.  It's the first one that lead me to write this issue.  Please feel free to close this issue.

```
PatientLevelPrediction$ grep -i getDbplpData man/*

man/createStudyPopulation.Rd:\code{getDbplpData}.}
man/fitGLMModel.Rd:\code{getDbPlpData}.}
man/savePlpData.Rd:\code{getDbPlpData}.}
```

**Comment by jreps** [comment]
thanks - I'll update these asap :)
