### ISSUE TITLE
Using deprecated features in `reticulate`?

### ISSUE THREAD

**Issue by aki-nishimura** [OHDSI/PatientLevelPrediction#204]
I had to make a series of changes to the code to get the function `configurePython` to work with the latest `reticulate` version on macOS Catalina:
https://github.com/aki-nishimura/PatientLevelPrediction/commit/7f5e9b063d645e9f7a23ee67c2e1cac852c833b7
https://github.com/aki-nishimura/PatientLevelPrediction/commit/b9965ebcf7a30bc0e65dbd528b8f7cc44198404f
https://github.com/aki-nishimura/PatientLevelPrediction/commit/fd0cde1f7b8ff5a61125a2e60557038d8a53356a

I am not sure about the older reticulate versions though.

**Comment by jreps** [comment]
We can update the required reticulate version and make these edits :)

**Comment by aki-nishimura** [comment]
Thanks @jreps. 

Upon further investigation, it seems more like an error due to "copy and paste" of the corresponding commands for `conda` to `virtualenv`:
https://rstudio.github.io/reticulate/reference/conda-tools.html

So I will go ahead and make a pull request without the change in required reticulate version.

**Comment by jreps** [comment]
Thank you
