### ISSUE TITLE
Warning 'no outcomes left' does not show

### ISSUE THREAD

**Issue by AniekMarkus** [OHDSI/PatientLevelPrediction#205]
**Describe the bug**
Warning is not given because it is preceded by a return statement. 

StudyPopulation.R lines 389-393
    # check outcome still there
    if(sum(!is.na(population$daysToEvent))==0){
      return(NULL)
      ParallelLogger::logWarn('No outcomes left...')
    }

**Additional context**
Change to:

    # check outcome still there
    if(sum(!is.na(population$daysToEvent))==0){
     ParallelLogger::logWarn('No outcomes left...')
     return(NULL)
    }

**Comment by jreps** [comment]
Made the edit - thanks
