### ISSUE TITLE
save models as json files for transparency

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#218]
**Is your feature request related to a problem? Please describe.**
The GLM are saved inside the plpModel, the python models are saved as pickles, the GBM models are saved as a GBM format and the Keras models are saved in their own format.  This is not very transparent.

**Describe the solution you'd like**
It would be nice to consistently save all the models as json objects

**Additional context**

- The GLM could easily be made into a json object as it is just a table
- the python models to json are mostly supported by https://pypi.org/project/sklearn-json/ 
- GBM may be as simple to just add .json: xgb.save(bst, 'model_file_name.json') (https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html) 
- Keras is probably the hardest to figure out if we want to continue training: https://keras.rstudio.com/articles/saving_serializing.html

**Comment by ted9219** [comment]
I agree with your opinion. It can be a good solution for model transparency and dealing with multiple models.

**Comment by jreps** [comment]
where possible models are now saved as json files
