### ISSUE TITLE
Running Naive Bayes 

### ISSUE THREAD

**Issue by julwa** [OHDSI/PatientLevelPrediction#235]
**Describe the bug**

When defining a PLP in Atlas Version (2.8.1).  and adding Naive Bayes to the Analysis setting I get and error when running the model. using the following procedure: 

1) Define PLP model in Atlas 
2) Download study package
3) execute study package in Rstudio 

**Set up (please run in R "sessionInfo()" and copy the output here):**
(session info) 
![image](https://user-images.githubusercontent.com/73587338/132484147-ffb20ab1-8d90-4b0b-9880-10c66d387f8c.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/73587338/132484551-b59f32b8-de88-4adc-b275-94b4440d3039.png)

**PLP Log File**
![image](https://user-images.githubusercontent.com/73587338/132484614-0516f9a6-c18b-4708-a65f-e7117fbe5b57.png)

**log.TXT**
![image](https://user-images.githubusercontent.com/73587338/132484796-5741e409-09aa-4171-bbc7-3d0f20158bcd.png)
![image](https://user-images.githubusercontent.com/73587338/132484862-0ca10a78-13ec-4243-97a0-a8bc46066169.png)

**Comment by julwa** [comment]
I tried to look a bit more into the issue. 

We ran the the installation check on our database.
PatientLevelPrediction::checkPlpInstallation(connectionDetails = connectionDetails,
python = T)

which calls the checkPlpInstallation function (HelperFunctions.R )(https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/HelperFunctions.R)

As I understand the checkPlpInstallation uses simulatePlpData function to create a little data set to check if all software has been properly installed and all models can run. 
Looking a bit closer at the simulated data (simulatePlpData(plpDataSimulationProfile, n = 10000, useInt64 = T). Lets call it the simulated_plpData. We discovered that it lacks the simulated_plpData$covariateData object since no informations is stored however the class definition is "CovariateData". 
simulated_plpData object can complete the execution of the Naive Bayes model succesfully.
 
![image](https://user-images.githubusercontent.com/73587338/135427930-d93b60d1-54d1-4579-a9af-239076a30ac2.png)


Hoewever when we load the plpData from our database which has the $covariateData object we have the following error in the plplog.txt

![image](https://user-images.githubusercontent.com/73587338/135438697-0c8fea63-8694-45c9-be59-5a20a4023dfa.png)

**Comment by jreps** [comment]
The simulated data for the version of PLP you are using should have covariateData ( https://github.com/OHDSI/PatientLevelPrediction/blob/14cf29ed4064698a896cea146a5c3be3835af305/R/Simulation.R ) and I think it must be there for Naive Bayes to run to completion with the simulated data.  If the simulated works fine, then there may be something off in the real data.   The error message suggests it may be that something is being covered into a 2-D array rather than a 1-D from R to python - I'll run some real data tests for Naive Bayes with the latest PLP to see whether I can reproduce the issue.  

Thanks for letting me know about this bug.

**Comment by julwa** [comment]
Regarding the simulated data. When i run the following lines of code from (https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/HelperFunctions.R) that calls the Simulation.R script

  plpDataSimulationProfile <- NULL
  e <- environment()
  utils::data(plpDataSimulationProfile, envir = e)
  sampleSize <- 2000
  plpData <- simulatePlpData(plpDataSimulationProfile, n = sampleSize)
  
  The plpData$covariateData is in my case empty, but it could be something wrong on our side.  

![image](https://user-images.githubusercontent.com/73587338/135458603-2314a757-8706-46fb-afca-f08c619b1ddb.png)

Hope this helps.

**Comment by jreps** [comment]
Ah, yeah, setting plpDataSimulationProfile to NULL will cause the covariate data to be empty :). There is a data object in the package for plpDataSimulationProfile that needs to be used instead.  You can see the object if you run: 

library(PatientLevelPrediction)
data(plpDataSimulationProfile)
