### ISSUE TITLE
Group shinkage (e.g. group lasso) during variable selection

### ISSUE THREAD

**Issue by pancodia** [OHDSI/PatientLevelPrediction#24]
Does a prediction model with variable selection procedure (e.g. lasso regression) consider group shinkage (e.g. group lasso)? For example, if a categorical variable with C levels is converted to C-1 binary features (i.e. dummy variables), it would make more sense that all C-1 variables are kept or removed after variable selection.

**Comment by jreps** [comment]
The current lasso logistic regression we use has group lasso but it is still being tested.  Hopefully it will be added this year.

**Comment by egillax** [comment]
This is not in scope at the moment. And since no more people have requested this in 6.5 years I'll close this.
