### ISSUE TITLE
PLP Restructuring

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#242]
The PLP code has been written to be backwards compatible but this has resulted in messy code.  As we have renv in the study packages (so backwards compatibility is less important), it seems like a good time to restructure the code.

- create setting functions when possible [ x] 
- modify runPlp to be modular [x]
- add featureEngineering settings into runPlp [x]
- add function to split plpData into train/test (or just CV) into runPlp [x]
- add over/undersampling setting into runPlp [x]
- rename files in /R be to more intuitive []
- move the function to test that PLP runs into /extras [x]
- update documentation [x]
- revise tests to make them run faster [x]

**Comment by egillax** [comment]
@jreps I just noticed that in the new branch no plots are saved/performed outside of shiny. Then when I try to run plotPlp on the results object of my analysis I get an error. Is the shiny using different plot functions then? In my case at least I think it would be useful to be able to run the individual plot functions at least, sometimes tweaking parameters to get the plot looking like you want it. 
 
 Maybe others have an opinion on if runPlp should still run plotPlp and make/save all the plots? Also shiny is currently a suggest dependency, but if it is required to view the results and no regular plots are made it probably should be a required dependency.

**Comment by jreps** [comment]
Hello, do you have the code you tried to run?  The plotting is still in branch issue 242 (see https://github.com/OHDSI/PatientLevelPrediction/blob/issue242/R/Plotting.R ) but was updated so has slightly different inputs.  Now the plotting does the plots per evaluation type, so you don't need to specify that you want to plot 'test' only, it will do any evaluation type in your results.

The shiny plots are slightly different now, they do the plot per evaluation and let you select which one to focus on, rather than using a grid to show all the evaluation types.

Note: The smooth calibration currently has an issue - I need to fix that.  The issue is cause by the prediction object using evaluationType by default to save the types and the performance evaluation objects using evaluation, I need to make two inputs into smooth calibration to specify these, since they can differ.

**Comment by egillax** [comment]
I dug a little bit. Turns out I was getting an error from plotVariableScatterplot because I skipped the runCovariateSummary when calling runPlp. Maybe an if statement should be added in case the plpResult$covariateSummary is not null so plotPlp skips that one if it doesn't exits?

**Comment by jreps** [comment]
perfect - this is the exact sort of issue I was hoping people would find before making this the master branch.  I should add a tryCatch to all the plots inside plotPlp() to make sure one failing doesn't cause the whole thing to fail.

**Comment by jreps** [comment]
I've now added tryCatches around all the plotting
