### ISSUE TITLE
Remove RSQLite dependency

### ISSUE THREAD

**Issue by ablack3** [OHDSI/PatientLevelPrediction#245]
I think it would reduce coupling and not impact performance to remove the use of RSQLite to access Andromeda objects. I'd like to have the Andromeda package expose a tested API that handles all of its use cases. Other packages that use Andromeda like PLP would use the API (function calls). I think Andromeda currently supports all of the uses in PatientLevelPrediction through function calls that don't require RSQLite. I have put together a PR that outlines what this change would look like. However I have not tested my changes. (I have not successfully run all the PLP package tests on my computer yet.)

**Comment by jreps** [comment]
I'm about to pull the issue_242 branch into develop and then master (there have been big changes to the code).  I think the only RSQLite stuff in issue_242 is the SQL with the limit here (and a count(*) which is definitely unnecessary): https://github.com/OHDSI/PatientLevelPrediction/blob/issue242/R/AndromedaHelperFunctions.R.  I like your solution to the limit.  I'm just going to check the speed before pulling any edits though (I don't see any obvious reason it would be slower but I want to double check).

Would you like to make the edits and create a pull request for issue_242 or shall I?

**Comment by ablack3** [comment]
I'll redo my PR to target the issue242 branch later today. I'll let you handle testing though if that's ok :)

**Comment by ablack3** [comment]
I merged issue242 into my develop branch and then created a PR on the issue242 branch. https://github.com/OHDSI/PatientLevelPrediction/pull/248

**Comment by jreps** [comment]
I've added in a sqlite database to save the PLP results (from multiple runs) so PLP needs sqlite now.  We could look at alternative databases in the future though.

**Comment by ablack3** [comment]
Ok. I think the issue here was that PLP was using Andromeda as a database connection which does not allow me to change the backend from SQLite to Arrow. If you're using SQLite independently of Andromeda that is totally fine.

**Comment by ablack3** [comment]
I'll close this for now noting that changes to PLP might still be required to use the Andromeda-arrow implementation.
