### ISSUE TITLE
Temporal Data

### ISSUE THREAD

**Issue by melissarost** [OHDSI/PatientLevelPrediction#25]
@PRijnbeek, we're really excited to start using temporal data since hearing that code was merged at the hack-a-thon. I looked around and found the `inst/python/create_files_doctor_ai.py` file that seems to get the data in that format. From reading the code, it seems that the input file for this script is a file with 4 columns: the first one that is not used, patient id, covariate id, and then time id. Is this correct or is there any other formatting of that file that I'm missing? I created a little sample .csv file in this format to test the code.

Also, from reading the code, it seems that the first covariate and time for a patient is actually lost if the data is in the form I described above. This is due to setting the value to an empty dictionary and list in lines 24 and 27 in that file, respectively. I fixed this on my version of the code, so I would be happy to put in a pull request and push that back up if that truly is an error.

Thanks!
Melissa

**Comment by sidsearch** [comment]
@melissarost, Actually you are right. When I wrote the code over last weekend, I did not think through that. I think by adding the cov_id in the "if condition for dictionary creation(line 26)" will fix the issue or if you have written it some other way that should fix it too!

Thanks!
Siddharth

**Comment by PRijnbeek** [comment]
Hi Melissa,

Yes we have seen this too. The code is currently in a feature branch and is thus under development this means it will change. 
it is not part of the PLP package release yet. We will write instructions on using the temporal feature extraction (which creates the input files for the conversion script) etc once we merge to master.

Good to see you like to try this out!

Peter

**Comment by melissarost** [comment]
Great! I would definitely like to see how the input files are created. I just put in a pull request with my changes to fix this error of the first entries being left off as well as improved efficiency in the second section.

**Comment by xypan1232** [comment]
Hi @melissarost, @sidsearch , 

After merging the changes from @melissarost with my changes, now the training for doctorAI works in our example data.

python doctorAI.py /data/home/xpan/PatientLevelPrediction/inst/python/visit  1526 /data/home/xpan/PatientLevelPrediction/inst/python/visit 1526 outfiles
Using cuDNN version 5110 on context None
Mapped name None to device cuda: TITAN X (Pascal) (0000:83:00.0)
Initializing the parameters ...  using randomly initialized code embedding
Building the model ...  not using duration information, fine-tuning code representations
Loading data ...  done
Optimization start !!
epoch:0, mean_cost:2.108679
Validation cross entropy:3.025709 at epoch:0
Test cross entropy:3.215326 at epoch:0
epoch:1, mean_cost:2.107733
Validation cross entropy:3.025156 at epoch:1
Test cross entropy:3.214357 at epoch:1
epoch:2, mean_cost:2.106780
Validation cross entropy:3.024601 at epoch:2
Test cross entropy:3.213384 at epoch:2
epoch:3, mean_cost:2.105823
Validation cross entropy:3.024044 at epoch:3
Test cross entropy:3.212406 at epoch:3
epoch:4, mean_cost:2.104864
Validation cross entropy:3.023486 at epoch:4
Test cross entropy:3.211424 at epoch:4
epoch:5, mean_cost:2.103898
Validation cross entropy:3.022925 at epoch:5
Test cross entropy:3.210437 at epoch:5
epoch:6, mean_cost:2.102932
Validation cross entropy:3.022363 at epoch:6
Test cross entropy:3.209448 at epoch:6
epoch:7, mean_cost:2.101963
Validation cross entropy:3.021801 at epoch:7
Test cross entropy:3.208456 at epoch:7
epoch:8, mean_cost:2.100991
Validation cross entropy:3.021237 at epoch:8
Test cross entropy:3.207460 at epoch:8
epoch:9, mean_cost:2.100016
Validation cross entropy:3.020670 at epoch:9
Test cross entropy:3.206459 at epoch:9
The best valid cross entropy:3.020670 at epoch:9
The test cross entropy: 3.206459

**Comment by jreps** [comment]
There is also a new modification for mapping the temporal data into a python sparse tensor, you can select the temporal flag in to toSparsePython:
toSparsePython(plpData,population, map=NULL, temporal=T)
