### ISSUE TITLE
[issue 242] cannot be compatible with a current PLP json file

### ISSUE THREAD

**Issue by ted9219** [OHDSI/PatientLevelPrediction#251]
**Describe the bug**

Cannot read predictionAnalysisList file using the loadPlpAnalysesJson function (branch issue242 only -  #242).
Please find the error log below.

```r
Issue with loading json file...
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.
Error in if (encoding.mode == "NULL") {: argument is of length zero
```

A line mentioned the tryCatch seems to be related to the updated ParallelLogger (3.0.0)

**Set up (please run in R "sessionInfo()" and copy the output here):**

R 4.0.3 
PatientLevelPrediciton 5.0.0 - Issue242 branch
ParallelLogger 3.0.0
DatabaseConnector 5.0.0
SqlRender 1.8.3
SkeletonPredictionStudy ([here](https://github.com/OHDSI/SkeletonPredictionStudy/blob/issue242/inst/settings/predictionAnalysisList.json))

**To Reproduce**

```r
 predictionAnalysisListFile <- system.file("settings", "predictionAnalysisList.json", package = "DeepPLPTest")
  predictionAnalysisList <- PatientLevelPrediction::loadPlpAnalysesJson(predictionAnalysisListFile)
```

**Comment by jreps** [comment]
This should be fixed now.  I've added the latest json into the skeleton package and also added code to make it (mostly) backwards compatible (except it uses default hyper-parameter settings)

**Comment by ted9219** [comment]
Oh, one thing I found is that if the splitSeed in JSON file, then the backwards function throws an error like this.

ERROR	PatientLevelPrediction	checkIsClass	splitSeed should be of class:numericsplitSeed should be of class:integer

it seems that because that NULL is into createDefaultSplitSetting (splitSeed = json$runPlpArgs$splitSeed).
