### ISSUE TITLE
[issue 242] Hard coded saveDirectory = 'D:/test/plp'

### ISSUE THREAD

**Issue by sdotter** [OHDSI/PatientLevelPrediction#252]
I noticed this wouldn't work on systems without a d drive or linux etc...

https://github.com/OHDSI/PatientLevelPrediction/blob/934e1f8e41ca6d3834e0afc9f938f7bb8ba8c06c/tests/testthat/helper-objects.R#L71

Maybe saveLoc + temp or something?

**Comment by jreps** [comment]
Thanks, that was a mistake.  That is the location I use when I run tests locally if I want to easily check things, I've now edited the code to use saveLoc instead of 'D:/test/plp'
