### ISSUE TITLE
Please update installation instructions

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#254]
Both the [Quick install guide](https://ohdsi.github.io/PatientLevelPrediction/articles/PatientLevelPrediction.html) and the [Installation guide](https://ohdsi.github.io/PatientLevelPrediction/articles/InstallationGuide.html) are outdated for the following reasons:

1. Both say that `drat` is the recommended approach to installing the package. This should be using `remotes` instead, like all other HADES packages.
2. Mentioning `devtools`, while `remotes` is preferred (`devtools` calls `remotes`, so does the same thing, but has a lot more dependencies)
3. Both suggest that the 'master' branch contains the latest develop version. This branch has been renamed to 'main', and also only contains the latest released version. The `develop` branch should contain the latest develop version.

I also recommend linking to the [HADES page on setting up R, RTools, RStudio, and Java](https://ohdsi.github.io/Hades/rSetup.html).

**Comment by jreps** [comment]
fixed in issue242 branch (will be pulled to main soon)
