### ISSUE TITLE
RandomForest() Error

### ISSUE THREAD

**Issue by bechlerk** [OHDSI/PatientLevelPrediction#255]
Hi! Most models work fine, but the RandomForest model generates an error that looks related to python packages. I ran "checkPlpinstallation" with python = T, and everything ran smoothly except for this error at the end:

"Checking support for large data objects
Error in ff(initdata = initdata, length = length, levels = levels, ordered = ordered,  : 
  vmode 'character' not implemented"

I then also ran the code to confirm I have a python environment:
library(PatientLevelPrediction)
reticulate::install_miniconda()
configurePython(envname='r-reticulate', envtype='conda')

And get errors like the below:
Error: 'install_miniconda' is not an exported object from 'namespace:reticulate'
Error: Unable to find conda binary. Is Anaconda installed?

I would appreciate any help in troubleshooting how I can fix my python environment. I am currently using a docker container. Please let me know if there's any additional information that would be helpful.

**Comment by jreps** [comment]
Hello,

I think there may be a couple of issues:

1. The error "Error: 'install_miniconda' is not an exported object from 'namespace:reticulate'" suggests that you may have an older version of reticulate installed.  I think updating reticulate to the latest version should fix that error.  I need to check the DESCRIPTION file to make sure I have the correct minimum version specified.
2. The ff error seems like there may be an issue with the data.  In later versions of PatientLevelPrediction we have removed the dependency on ff and use Andromeda instead.  Are you just using R or do you also use ATLAS to design your prediction?  The reason I ask, it that ATLAS is not up to date with the latest PatientLevelPrediction package, so if you are using ATLAS it will not be compatible with the most recent PatientLevelPrediction until ATLAS is updated.  I can give you instructions to install the most recent PatientLevelPrediction that is compatible with ATLAS though. If you are not using ATLAS I can give you instructions to install the most updated PatientLevelPrediction.  Both of these will fix the ff error.

Best wishes,
Jenna
