### ISSUE TITLE
Drop `rms` and `Hmisc` dependencies

### ISSUE THREAD

**Issue by rekkasa** [OHDSI/PatientLevelPrediction#260]
**Is your feature request related to a problem? Please describe.**
The package has a quite large number of dependencies, especially when compared to other `HADES` packages, such as `CohortMethod`

**Describe the solution you'd like**
Packages `rms` and `Hmisc` have a very large number of dependencies, often not required by any other package in the dependency list (see screenshot below). I think the only need for these packages is estimation of the E-statistics (E_avg, E90, ...) and plotting smooth calibration using restricted cubic splines (RCS). 

**Describe alternatives you've considered**
Calculating the E-statistics is pretty straightforward and can be done in a few lines of code (I have already implemented that locally). For estimating the RCS fit we could use the functions from `mgcv` package, which is already present due to`ggplot2` depending on it. We can create the exact same plots as `rms::rcs(...)` just by following the knot placement implemented in `rms` (I also have written the code for it).

I can implement these changes if you agree @jreps 

**Dependency network**
![dependency_network](https://user-images.githubusercontent.com/37042404/155758731-9bd1f337-c73f-414b-808b-724c2e7aa690.png)

**Comment by jreps** [comment]
Excellent work.  I've been wanting to remove Hmisc (I think the only current use is for splitting a vector) for a while and if you have code to remove rms that would be fantastic!  Definitely happy for you to make these changes.

**Comment by jreps** [comment]
This was fixed by Alex
