### ISSUE TITLE
Failure to adhere to coding standards

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#27]
According to [our R code style guide](http://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_code_style_for_r#case) function names should start with a lower case letter.

[**R**unPlp](https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/RunPlp.R#L130) currently violates that rule.

Seriously, I know at least one user (not me) that was tripped up by this ;-)

**Comment by edlee123** [comment]
Maybe something like the package lintr could be helpful, and then set up a standard config to go with the project?

**Comment by schuemie** [comment]
I tried lintr in the past, but found it to be of limited value. I don't remember the exact reasons, but I think it was because the conventions required by lintr were incompatible with the conventions we use and there is no way to customize lintr. One specific thing I remember is that lintr was incompatible with formatr so some of the auto code formatting would be flagged as incorrect.

**Comment by PRijnbeek** [comment]
Best I think is if we just adhere to the conventions and fix this.
I will update the package and study code and will change RunPlp to runPlp.

Thanks Martijn for pointing us to this big violation of the rules :)

**Comment by edlee123** [comment]
It is possible to customize the conventions in lintr so that it flags as you please, though you're right, it  won't make the corrections automatically (formatR does some of this).   Managing lint in R can get painful as more people join

**Comment by edlee123** [comment]
I customized a .lintr config with OHDSI style conventions, and get:

                          linter    n
1            infix_spaces_linter 2047
2                  commas_linter 1291
3             line_length_linter  750
4              snake_case_linter  416
5 spaces_left_parentheses_linter  377
6              assignment_linter   57
7                  no_tab_linter   19

1, 2 and 3 are very fixable with formatR
