### ISSUE TITLE
Different starting point for population

### ISSUE THREAD

**Issue by rekkasa** [OHDSI/PatientLevelPrediction#271]
**Is your feature request related to a problem? Please describe.**
Function `createStudyPopulation` has a _population_ input for specifying a different starting point instead of `plpData$cohorts`. This functionality is not accessible from `runPlp`

**Describe the solution you'd like**
Use a subset of `plpData$cohorts` as the starting point for study population generation

**Describe alternatives you've considered**
I have tried swapping `plpData$cohorts` with the subset I want, but it is not a clean solution. Maybe add a _population_ input to `runPlp` which can then be passed on to `createStudyPopulation`?

**Additional context**

**Comment by jreps** [comment]
maybe we should have a population in plpData that gets used in preference of plpData$cohorts if it is there? We may want to play around with some potential solutions and see which feels the best?

**Comment by jreps** [comment]
In the develop branch I added 'population = plpData$population' on line 279 of RunPlp.R - if you set the population in your plpData then it will start with that population otherwise this is NULL and it uses plpData$cohorts.  Hopefully that fixes your issue?

**Comment by rekkasa** [comment]
Great! Yes, that would fix it. You can close the issue, if you want.

**Comment by jreps** [comment]
fixed in the main branch now
