### ISSUE TITLE
Save runPlp result as an sqlite database

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#272]
**Is your feature request related to a problem? Please describe.**
The shiny app reads three different inputs: 1) runPlp object, 2) file location and 3) database backend.  The run multiple plp analyses code saves runPlp objects as rds files spread across different directories - understanding how the results are related and how to access the results is currently not very intuitive. 

**Describe the solution you'd like**
If we save the runPlp object as an sqlite database: 
- we could just use the database interface for the shiny app which makes the shiny app code cleaner
- the run multiple plp analyses would be saved into a single sqlite database (single file) which clear relationships between tables, making it easier to see what the settings were (e.g., target population name, outcome name, etc).
- saving the runPlp objects into an sqlite database makes it very easy to export the results as csv files (each table would just be a separate csv file).
- you could have a single result location locally on your computer that you save all your runPlp models to.

This would just require updating the save/loadPlpResult

**Describe alternatives you've considered**
- we could save the runPlp to different easy to set up databases or straight to csv files 

**Additional context**
@egillax @chandryou @cynthiayang525  @rossdwilliams @ted9219 @lhjohn @rekkasa  interested in hearing everyones thoughts (I've tagged the usernames I could easily find but please share this with others I've not been able to tag).

**Comment by jreps** [comment]
added this in develop

**Comment by lhjohn** [comment]
Did you find what was causing https://github.com/OHDSI/PatientLevelPrediction/issues/291? I had it in `database_results`, but not in `develop`.

**Comment by jreps** [comment]
fixed in the main branch now
