### ISSUE TITLE
Small breaking bug in validateMultiplePlp

### ISSUE THREAD

**Issue by tomseinen** [OHDSI/PatientLevelPrediction#279]
**Describe the bug**
validateMultiplePlp stops after validation of the first Analysis directory.

**To Reproduce**
Run validateMultiplePlp on a directory with multiple Analysis_# directories.

**Additional context**
The problem is caused by trying to index an object with only one string.
Very simple fix: remove the [i] after modelSettings in the IF statement.

https://github.com/OHDSI/PatientLevelPrediction/blob/f0cdc5c60a2045de66fc8c98374ffcab8ed9ac63/R/RunMultiplePlp.R#L446

**Comment by jreps** [comment]
Fix in new release - thanks for letting us know about this
