### ISSUE TITLE
Issues in source code

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#28]
We have a somewhat useful function called `checkUsagePackage` in OhdsiRTools for detecting problems in source code. In fact, it is [referenced in PackageMaintenance.R](https://github.com/OHDSI/PatientLevelPrediction/blob/master/extras/PackageMaintenance.R#L21).

For the PLP package, it generates the output below. 

The first lines have to do with the fact that some variable names have the same name as functions, and it might be good to adhere to our guideline of making function names a combination of a verb and a noun (e.g. computeAccuracy() instead of [accuracy()](https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/EvaluatePlp.R#L702)).

The last lines point out that there's a [typo in calling a function](https://github.com/OHDSI/PatientLevelPrediction/blob/master/R/RunMultiplePlp.R#L121).

`
getThresholdSummary: local variable ‘accuracy’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:467)
getThresholdSummary: local variable ‘diagnosticOddsRatio’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:478)
getThresholdSummary: local variable ‘f1Score’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:466)
getThresholdSummary: local variable ‘falseDiscoveryRate’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:473)
getThresholdSummary: local variable ‘falseNegativeRate’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:469)
getThresholdSummary: local variable ‘falseOmissionRate’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:475)
getThresholdSummary: local variable ‘falsePositiveRate’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:470)
getThresholdSummary: local variable ‘negativeLikelihoodRatio’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:477)
getThresholdSummary: local variable ‘negativePredictiveValue’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:474)
getThresholdSummary: local variable ‘positiveLikelihoodRatio’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:476)
getThresholdSummary: local variable ‘positivePredictiveValue’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:472)
getThresholdSummary: local variable ‘sensitivity’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:468)
getThresholdSummary: local variable ‘specificity’ used as function with no apparent local function definition (C:/Users/mschuemi/git/PatientLevelPrediction/R/EvaluatePlp.R:471)
runPlpAnalyses: no visible global function definition for ‘setTimeAtRisks’
runPlpAnalyses: no visible global function definition for ‘setTimeAtRisks’
`

**Comment by jreps** [comment]
I finally cleaned all these :)
