### ISSUE TITLE
Dependency on non-CRAN, non-HADES package `IterativeHardThresholding`

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#281]
HADES packages should only depend on CRAN packages or other HADES packages. The current version of PatientLevelPrediction [depends on `IterativeHardThresholding`](https://github.com/OHDSI/PatientLevelPrediction/blob/main/DESCRIPTION#L61). Please either remove this dependency (and for example move this code either into PLP or Cyclops), or get `IterativeHardThresholding` into HADES.

Please fix ASAP, as this is breaking our ability to fully reproduce HADES packages (and for example breaks our [script for reverse dependency checking](https://github.com/OHDSI/.github)).

**Comment by rossdwilliams** [comment]
Hi Martijn,

This is a recent addition that is mostly for research purposes. We could move the iht dependency to suggests? @msuchard has done most development on the IHT package so it would be great to get his thoughts on whether it makes sense to absorb this code? 

Otherwise what is the process of adding a package to HADES?

**Comment by msuchard** [comment]
I can move `IHT` into HADES; it does not belong in `PLP` and I'd like to keep `Cyclops` as modular as possible.

**Comment by msuchard** [comment]
moving into HADES mostly means:
1. change CI from `travis` to `githubActions`

**Comment by rossdwilliams** [comment]
okay thats completely fine @schuemie, good to know. @msuchard if you take that on it would be great and let me know if i can do anything.

**Comment by msuchard** [comment]
now on CRAN: https://cran.r-project.org/web/packages/IterativeHardThresholding/index.html
