### ISSUE TITLE
Cannot develop a Random forest model

### ISSUE THREAD

**Issue by ted9219** [OHDSI/PatientLevelPrediction#283]
**Describe the bug**
Cannot develop a model with Random forest algorithm. It seems that it cannot find the developed model in the temp folder.

**Set up (please run in R "sessionInfo()" and copy the output here):**
copy the system set up details including the R version and operating system details...
![image (1)](https://user-images.githubusercontent.com/42205861/176988404-b82951ff-ae36-488f-b624-25d524439c41.png)

**PLP Log File**

![image](https://user-images.githubusercontent.com/42205861/176988353-53b6f514-151d-4338-a4c3-9c42adb82f8e.png)

**Additional context**
Any idea?

**Comment by jreps** [comment]
I think there was a previous issue posted about the save location not working with linux as I used paste() - I think the error you are getting is the same issue.  If I remember, I used paste() because file.path() was causing an error with my Mac, but I'll see whether that is still the case and try to fix this asap.

**Comment by ted9219** [comment]
or we can add Sys. info()[[1]] for identifying the os of the user, so we can divide the code using the if statement according to their os. 

if(Sys.info()[[1]] == 'Linux') {
modelLocation <- reticulate::r_to_py(paste0(plpModel$model,"/model.json"))
} else { 
modelLocation <- reticulate::r_to_py(paste0(plpModel$model,"\\model.json"))
}

**Comment by jreps** [comment]
I added (hopefully) the fix to this branch: https://github.com/OHDSI/PatientLevelPrediction/tree/database_results but this branch has some big changes as the shiny app uses the OhdsiShinyModules package and requires an sqlite database (that is automatically created during runMultiplePlp).

**Comment by jreps** [comment]
I fixed this in the current develop branch hopefully

**Comment by jreps** [comment]
fixed in the main branch now
