### ISSUE TITLE
loadPredictionAnalysisList is not an exported object from 'namespace:PatientLevelPrediction'

### ISSUE THREAD

**Issue by andtsouch** [OHDSI/PatientLevelPrediction#288]
**Describe the bug**
I am executing a patient level prediction study package generated by Hydra0.3.0 on R4.2.0 and PatientLevelPrediction5.0.5 and I am getting the following error when predictions are starting to run (just right after the cohorts are generated):
'"INFO"' is not an exported object from 'namespace:PatientLevelPrediction'.
From the log.txt I can see that the loadPredictionAnalysisList onject is not part of PatientLevelPrediction. Is there a way to run the execute() function avoding that?

**Set up (please run in R "sessionInfo()" and copy the output here):**
See below jpeg attached 'sessioninfo'

**To Reproduce**
See below jpeg attached 'codetorun'.

**PLP Log File**
See below jpeg attached 'logtxt'.

**Additional context**
![sessionInfo](https://user-images.githubusercontent.com/59889084/178462093-e2f960e9-0815-45a2-a912-284327b33b62.JPG)
![logtxt](https://user-images.githubusercontent.com/59889084/178463847-0254b22a-8e8a-4bad-b5dd-96bff64e2f37.JPG)
![codetorun](https://user-images.githubusercontent.com/59889084/178464032-353fdc3c-65c4-4602-8be3-8cc0ddec735d.JPG)

**Comment by solis9753** [comment]
I am not sure for the right answer.
Seems like loadPredictionAnalysisList is deprecated, or at least was there in PLP version 4.3.10.

**Comment by andtsouch** [comment]
The package name was created also from ATLAS causing the built of the package to push back to the old functions.

**Comment by nadavrap** [comment]
I got the same error. The issue is that I generated a PatientPrediction package from ATLAS 2.9 and my PLP R package version is the latest: 5.0.5.
When I tried a different ATLAS, version 2.11.0, I got the same error when executing the analysis.

**Comment by andtsouch** [comment]
I personally generate the study package using the Hydra package from HADES and not from ATLAS, since our ATLAS version is quite old. You can see how to easily do that here: https://ohdsi.github.io/Hydra/articles/HydratingPackages.html. You only need to copy the json file of the study from ATLAS:
