### ISSUE TITLE
No such function removePython

### ISSUE THREAD

**Issue by nadavrap** [OHDSI/PatientLevelPrediction#289]
When something goes wrong with `configurePython`, a help message appears:
```
Error: one or more Python packages failed to install [error code 1]
In addition: Warning message:
In configurePython(envname = "r-reticulate", envtype = "conda") :
  Conda environment r-reticulate exists.  You can use removePython() to remove if you want to fresh config
```

But, there is no such function, `removePython` not in the [PatientLevelPrediction](https://github.com/OHDSI/PatientLevelPrediction) package, nor in the reticulate package. So the message in [HelperFunctions.R](https://github.com/OHDSI/PatientLevelPrediction/blob/main/R/HelperFunctions.R) is not informative enough (or wrong?).

**Comment by jreps** [comment]
Hmm, not sure why that message is displayed. This is another good first commit for people who want to contribute to the code.  All that is needed is to change the text on lines 104 and 117 in HelperFunctions.R

**Comment by jreps** [comment]
I updated this message in the develop branch

**Comment by jreps** [comment]
fixed in the main branch now
