### ISSUE TITLE
Failed to test checkPlpInstallation due to undefined populationSettings

### ISSUE THREAD

**Issue by nadavrap** [OHDSI/PatientLevelPrediction#290]
**Describe the bug**
After a clean installation of the package, and following the installation guide of the PLP package, the call to `check` fails.

```
checkPlpInstallation(
  connectionDetails = connectionDetails, 
  python = T
  )
```

The output is:

```
Checking Models
Use timeStamp: TRUE
Creating save directory at: /tmp/RtmpFHSIKU/test1
Error in runPlp(plpData = plpData, outcomeId = 2, analysisId = "test1", : object 'populationSettings' not found
```

I identified line 72 in [PatientLevelPrediction](https://github.com/OHDSI/PatientLevelPrediction/tree/a1ee7cc9b8a439af732c3e4e319c9c8b761609cf)/[extras](https://github.com/OHDSI/PatientLevelPrediction/tree/a1ee7cc9b8a439af732c3e4e319c9c8b761609cf/extras)/checkPlpInstallation.R
[Go to file](https://github.com/OHDSI/PatientLevelPrediction/find/a1ee7cc9b8a439af732c3e4e319c9c8b761609cf)
```
populationSettings = populationSettings,
```
Which I think should be:

```
populationSettings = popSettings,
```

**Comment by jreps** [comment]
Good spot!  The quickest edit would be to replace 'popSettings' with 'populationSettings' on lines 33 and 50 in the develop branch.  I've tagged this as a good first commit for people looking to contribute to the code.

**Comment by jreps** [comment]
I made this edit to the develop branch - so this will be fixed when I pull develop into main.

**Comment by jreps** [comment]
fixed in the main branch now
