### ISSUE TITLE
Add covariates for provider specialty

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/PatientLevelPrediction#3]
Could have # of visits in past 365d  by specialty, and binary variable for specialty on index date.  Serves as interesting proxy for health behavior, but may also get at provider level effects (particularly important if interventions are services or device related)

**Comment by jreps** [comment]
With the current framework this is more of a FeatureExtraction request so I've opened it: https://github.com/OHDSI/FeatureExtraction/issues/59
