### ISSUE TITLE
PLP viewer error: argument imply differing number of rows

### ISSUE THREAD

**Issue by andtsouch** [OHDSI/PatientLevelPrediction#302]
Hi, 
I am executing and trying to visualize a PLP study using PLPv5.0.5. The execution runs through smoothly and finishes successfully. However, when I am trying to visualize the results using `PatientLevelPrediction::viewMultiplePlp(outputFolder)` the shiny application is opening as expected, but then nothing is possible to be viewed under the tab 'Explore Selected Model' (as seen in the attached). I am wondering if someone has had a similar error or it would be something that is wrong in my set-up. Thank you in advance.
![ShinyIssue_Visual](https://user-images.githubusercontent.com/59889084/184319233-73aa2a69-c4f1-4e7a-acc2-54681c6fa42a.jpg)
![ShinyIssue_sessionInfo](https://user-images.githubusercontent.com/59889084/184319237-0828273c-c947-4c08-84b2-b6de739473a9.jpg)

**Comment by nbehzad** [comment]
I either trained Lasso Logistic Regression on the development branch. The `plpResult` is complete (no errors), and I can manually plot all of the results successfully. However, when I launch the Shiny app to explore the model, **none of the plots can be loaded, and the plots remain in the loading state.**

**Comment by jreps** [comment]
Andi - I'm not sure what is causing this so I'm going to need to install PLP v5.0.5 and run a study using the ATLAS json spec.  Will update once I figure out the issue. 

nbehzad - The PatientLevelPrediction develop branch is now using the OhdsiShinyModules package for the shiny code. Make sure you have the latest version of that package and try viewPlp() if you have result <- runPlp() or viewMultiplePlp() if you ran runMultiplePlp().  I just tested all the models and the shiny app with the latest develop branch and it was working for me.

**Comment by andtsouch** [comment]
@jreps thanks for looking into it, let me know if there is something I can test from my side. I am curious if someone else is also facing this issue.

**Comment by nbehzad** [comment]
@jreps I am using the OhdsiShinyModules package for the shiny code, but when I run it, I get the following error. **Error in : Could not connect to database: unable to open database file** 
The runMultiplePlp function is run without error, and the database file is generated successfully. **Do you have any idea where the issue is coming from?**
