### ISSUE TITLE
Incompatibility between PLP develop branch and EnsemblePLP package

### ISSUE THREAD

**Issue by nbehzad** [OHDSI/PatientLevelPrediction#306]
**Describe the bug**
The `runMultiplePlp` function is used by the `runEnsemble` function in the `EnsemblePLP` package. However, in the develop branch, the `splitSettings` parameter has been removed from the `runMultiplePlp` function, resulting in errors when running `runEnsemble`.

**runEnsemble.R in the EnsemblePLP package**
```sh
    PatientLevelPrediction::runMultiplePlp(
      databaseDetails = ensembleSettings$databaseDetails,
      modelDesignList = ensembleSettings$modelDesignList,
      onlyFetchData = F,
      splitSettings = ensembleSettings$splitSettings,
      logSettings = logSettings,
      saveDirectory = saveDirectory
    )
```
**RunMultiplePlp.R in the develop branch**
```sh
runMultiplePlp <- function(
  databaseDetails = createDatabaseDetails(),
  modelDesignList = list(
    createModelDesign(targetId = 1, outcomeId = 2, modelSettings = setLassoLogisticRegression()), 
    createModelDesign(targetId = 1, outcomeId = 3, modelSettings = setLassoLogisticRegression())
  ),
  onlyFetchData = F,
  cohortDefinitions = NULL,
  logSettings = createLogSettings(
    verbosity = "DEBUG", 
    timeStamp = T, 
    logName = "runPlp Log"
  ),
  saveDirectory = getwd(),
  sqliteLocation = file.path(saveDirectory, 'sqlite')
)
```

**Comment by jreps** [comment]
This should be fixed in this branch: https://github.com/OHDSI/EnsemblePatientLevelPrediction/tree/plp540 

I plan to pull both into the main branch together soon.

**Comment by jreps** [comment]
I should have a develop branch for EnsemblePLP though (that works with the PLP develop)- let me make that now

**Comment by jreps** [comment]
fixed in the main branch now
