### ISSUE TITLE
Inconsistency between the settings table and the modelDesignList in the RunMultiplePlp function in the develop branch

### ISSUE THREAD

**Issue by nbehzad** [OHDSI/PatientLevelPrediction#309]
**Bug Description**
In the following part of the `runMultiplePlp` funcion in the develop branch, when the `cohortDefinitions` is NULL and there is only one set of target and outcome cohort ids in all modelDesign objects, the condition `if (nrow(settingstable) != length(modelDesignList))` will never be FALSE and it will result in `stop('Error in settingstable')`    

```sh
  if(is.null(cohortDefinitions)){
    
    cohortIds <- unlist(
      lapply(
        X = 1:length(modelDesignList), 
        FUN = function(i){
          c(
            modelDesignList[[i]]$targetId,
            modelDesignList[[i]]$outcomeId
          )
        }
      )
    )
    
    cohortDefinitions <- lapply(
      X = cohortIds, 
      FUN = function(x){
        list(
          id = x, 
          name = paste0('Cohort: ', x)
        )
      }
    )
  
  }
  
  settingstable <- convertToJson(modelDesignList,cohortDefinitions)
  
  if(nrow(settingstable) != length(modelDesignList)){
    stop('Error in settingstable')
  }
```

For example, suppose you have the same target id 1 and outcome id 2 in all of the models below:
```sh
  modelDesignList = list(modelDesignLR, modelDesignRF, modelDesignAB, modelDesignGB, modelDesignNB)
```
`nrow(settingstable)` will be 125 while `length(modelDesignList)` will be 5. As a result, the following condition will always be TRUE:

```sh
  if(nrow(settingstable) != length(modelDesignList)){
    stop('Error in settingstable')
  }
```

When the `cohortIds` are unlisted, the count of ids is doubled, and the settings are repeated in the `convertToJson` function.

**Comment by jreps** [comment]
Good spot - I think this just needs a unique() around the unlist.  nrow(settingstable) should be length(modelDesignList) as there should be a setting row per model design, so if the settingstable has 125 rows for 5 model designs this is an error. 

I'll fix this on Monday.

**Comment by jreps** [comment]
Thanks for letting me know about this.  I added unique and checked the runMultiple with the same modelDesign except using a lasso LR for one and adaBoost for the other - it worked.  I committed this change (plus a few other fixes for feature engineering)

**Comment by nbehzad** [comment]
Thank you so much, @jreps ! 
I just tested it as well. Adding unique resolved the issue.

**Comment by jreps** [comment]
fixed in the main branch now
