### ISSUE TITLE
Bug in validateMultiplePlp function

### ISSUE THREAD

**Issue by nbehzad** [OHDSI/PatientLevelPrediction#313]
**Describe the bug**
The `validateMultiplePlp` function applies the `externalValidateDbPlp` function to each plp analysis in a loop, as shown below:
```sh
  for(i in 1:length(analyses)){
    
    if(is.null(saveDirectory)){
      saveLocation <- file.path(analysesLocation, 'Validation')
    } else{
      saveLocation <- saveDirectory
    }
    
    analysis <- analyses[i]
    modelSettings <- file.path(analysesLocation, analysis)
    
    ParallelLogger::logInfo(paste0('Evaluating model in ',modelSettings ))
    
    if(dir.exists(file.path(modelSettings[i],'plpResult'))){
      ParallelLogger::logInfo(paste0('plpResult found in ',modelSettings ))
      
      plpModel <- loadPlpModel(file.path(modelSettings,'plpResult','model'))
      
      validations <-   tryCatch(
        {
          externalValidateDbPlp(
            plpModel = plpModel,
            validationDatabaseDetails = validationDatabaseDetails,
            validationRestrictPlpDataSettings = validationRestrictPlpDataSettings,
            settings = createValidationSettings(
              recalibrate = recalibrate
            ),
            outputFolder = saveLocation
          )},
        error = function(cont){ParallelLogger::logInfo(paste0('Error: ',cont ))
          ;return(NULL)}
      )
      
    }
  }
```
The analysis file path for each analysis is set to `modelSettings`. However, it is checked by loop index [i] in the later if statement, which results in validating only the first analysis (analysis_1).
This `if(dir.exists(file.path(modelSettings[i],'plpResult')))` is only TRUE for i=1. As a result, the remaining analyses will never be validated, and no errors will be recorded in the log file.
I think the if statement should have been as follows: `if(dir.exists(file.path(modelSettings,'plpResult'))))`

**Comment by nbehzad** [comment]
@jreps I changed the if statement to `if(dir.exists(file.path(modelSettings,'plpResult')))` in my local package. It works, and the bug is resolved.

**Comment by jreps** [comment]
yeah - looks like the [i] is oddly added.  Thanks for this catch!  Do you want to make a pull request with the edit into the develop branch (happy to help guide if you are new to GitHub) or would you prefer me to make the edit?

**Comment by nbehzad** [comment]
Can I make a commit to the develop branch?

**Comment by nbehzad** [comment]
@jreps I just made a pull request to the develop branch. I incorrectly modified the RunMultiplePlp.R file from the main branch and so the `patch-1` was created from the main branch. **Does it cause a problem?** It may overwrite your changes in the develop branch if RunMultiplePlp.R differs between the main and develop branches. Sorry for the inconvenience!

**Comment by jreps** [comment]
fixed in the main branch now
