### ISSUE TITLE
seeds in model design may be problematic

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#316]
Some of the models or processes to develop a model have seeds that enable reproducibility.  These seeds are often in the settings.  I've noticed one potential issue with this, if a model design is exactly the same, except for a seed, in the database saving the model designs will be considered different (but technically they are the same).

Should we consider a logistic regression with a different start seed but all other settings to be the same model setting design or different?  Should we pull out seeds from the models designs and put these somewhere else?  Hope to hear thoughts from the community on this.  

Happy to clarify more if I've not been clear (please let me know if this does not make sense).

**Comment by egillax** [comment]
Just to make sure I understand.

- Current behavior: It will insert the model as a new model in the database if it has a different seed?
- Possible alternative: It will ignore the seed and overwrite/update an existing model in the database if the model design is the same?

**Comment by jreps** [comment]
Keeping seeds for now so closing this one
