### ISSUE TITLE
Inconsistent naming convention in decision tree functions

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#32]
The decision tree functions all [use snake_case instead camelCase for the arguments](https://github.com/OHDSI/PatientLevelPrediction/blob/develop/R/DecisionTree.R#L20). This is inconsistent with the rest of the package and the [OHDSI Code Style](http://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_code_style_for_r).

**Comment by jreps** [comment]
updated all classifiers to camelCase
