### ISSUE TITLE
External validation error on a single database with multiple cohort ids as subgroup evaluations.

### ISSUE THREAD

**Issue by nbehzad** [OHDSI/PatientLevelPrediction#320]
**Describe the bug**
This may not be considered a bug because this type of functionality may not be anticipated during the design of this function.

A single model can be validated on multiple databases using the `externalValidationDbPlp` function. However, when I want to validate a single model using multiple `validationDatabaseDetails` with **the same database names but different target ids** (demonstrating particular subsets of the target cohort), their results are overwritten. This is because the result of external validation is defined solely by the database name and analysis id.
This may be fixed by including the target id in the database name when saving the results.

**Comment by nbehzad** [comment]
Your solution is excellent, but it will necessitate a major change in this function and may bring new problems for the rest, such as displaying results in the Shiny app. Dividing the validation results within each database folder complicates things because each database folder will have a separate result folder for each model (analyze_id in the plpModel). For three models, we will have three folders: Analysis_1, Analysis_2, and Analysis_3 in each database directory.

I believe the current pipeline is excellent, and we can keep it while making a few minor modifications to resolve the issue without affecting the rest of the package. Therefore, my recommendation is to maintain the current pipeline and save the results as the following strategy:

In the createDatabaseDetails function, we can add a new attribute named "databaseDetailsName." `attr(result, "databaseDetailsName") <- databaseDetailsName`

**createDatabaseDetails function:**
```sh
function (connectionDetails, cdmDatabaseSchema, cdmDatabaseName, 
  tempEmulationSchema = cdmDatabaseSchema, cohortDatabaseSchema = cdmDatabaseSchema, 
  cohortTable = "cohort", outcomeDatabaseSchema = cdmDatabaseSchema, 
  outcomeTable = "cohort", targetId = NULL, outcomeIds = NULL, 
  cdmVersion = 5, cohortId = NULL) 
{
  if (is.null(targetId)) {
    if (!is.null(cohortId)) {
      ParallelLogger::logWarn("cohortId has been depreciated.  Please use targetId.")
      targetId <- cohortId
    }
  }
  result <- list(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, 
    cdmDatabaseName = cdmDatabaseName, tempEmulationSchema = tempEmulationSchema, 
    cohortDatabaseSchema = cohortDatabaseSchema, cohortTable = cohortTable, 
    outcomeDatabaseSchema = outcomeDatabaseSchema, outcomeTable = outcomeTable, 
    targetId = targetId, outcomeIds = outcomeIds, cdmVersion = cdmVersion)
  attr(result, "cdmDatabaseName") <- cdmDatabaseName
  class(result) <- "databaseDetails"
  return(result)
}
```

Its default value is a copy of cdmDatabaseName. In this scenario, everything will operate as usual. This value can be used as a folder name during validation. Consequently, anyone can assign any meaningful name to validation databases and create multiple databaseDetails with the same database and different names based on the database version or target id, or anything else. In the `externalValidationDbPlp` function, we only need to replace `cdmDatabaseName` with `databaseDetailsName` in a few lines as shown below: 

**externalValidationDbPlp function:**
```sh
  checkIsClass(settings, "validationSettings")
  result <- list()
  length(result) <- length(validationDatabaseDetails)
  names(result) <- unlist(lapply(validationDatabaseDetails, 
    function(x) attr(x, "databaseDetailsName")))
  for (databaseDetails in validationDatabaseDetails) {
    databaseName <- attr(databaseDetails, "cdmDatabaseName")
    databaseDetailsName <- attr(databaseDetails, "databaseDetailsName")
      ...
    result[[databaseDetailsName]] <- tryCatch({
      externalValidatePlp(plpModel, plpData, databaseName = databaseName, 
        population, settings = settings)
    }, error = function(e) {
      ParallelLogger::logInfo(e)
      return(NULL)
    })
     }
     ...
    savePlpResult(result[[databaseDetailsName]], dirPath = file.path(outputFolder, 
        databaseDetailsName, plpModel$trainDetails$analysisId, 
        "validationResult"))
```

I also agree to add a csv file to the /Validation (not to the Validation/database) directory that summarizes the validation on different databaseDetails settings.

As a result, for each `databaseDetailsName` we will have a folder including the validation results of all training models, and all validation results will be displayed in the Shiny app without any modification.

**Comment by jreps** [comment]
I like it!  Much easier and fixes the issue.

Do you want to make the edits and make a pull request or shall I make the edits?

**Comment by nbehzad** [comment]
I would appreciate it if you could make the changes because they may affect parts of the package about which I am unaware, or some additional changes may be required to comply with other functions. As a result, your edits will be more reliable than mine :)

**Comment by nbehzad** [comment]
I just resolved the issue in my local package. I also noticed and fixed another bug. It was about the `validationDatabaseDetails` class being checked within the `validateMultiplePlp` function. I will submit a pull request, and you can look into my changes.

**Comment by egillax** [comment]
Closing because in inactivity. External validity has also been improved quite a bit recently and a new function added that's very flexible: validateExternal.
