### ISSUE TITLE
addMultipleRunToPlpToDatabase error handling

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/PatientLevelPrediction#323]
I'd recommend adding a check to the code here: https://github.com/OHDSI/PatientLevelPrediction/blob/f4c5d9d526fe90a05a06743306d317826e19a5e1/R/uploadToDatabase.R#L307 to verify if the `resultLocationVector` contains a path with the results location. I made the mistake of not pointing to the correct folder and instead of erroring out, it appeared as if the function completed when in fact it just skipped the upload all together.

**Comment by jreps** [comment]
fixed in the main branch now
