### ISSUE TITLE
Possibility to accomodate a custom solution for multiple imputation

### ISSUE THREAD

**Issue by andtsouch** [OHDSI/PatientLevelPrediction#349]
Hi! I have been looking into the possibility to apply multiple imputation on the runPlp pipeline. Since imputation should be applied after the splitting of the data, so essentially on trainData and testData separately, an easy place that I can see for that to be added would be with a custom splitData function that could be used instead of the current one here:
https://github.com/OHDSI/PatientLevelPrediction/blob/main/R/RunPlp.R#L294
In that way the user could build code that would customize or change (e.g. impute) the trainData and testData objects that are returned by the spliData function(). I can see that there is a way to customize the splitSettings, but that can only provide the way splitIds are selected.

I can also see a benefit of having a placeholder for a custom function that could manipulate the data$train and data$test here: https://github.com/OHDSI/PatientLevelPrediction/blob/main/R/RunPlp.R#L325

I was therefore wondering if there could be a chance to provide one of these custom solutions in a future version or if you would have some better suggestions. Thank you in advance!

**Comment by solis9753** [comment]
Hi, others may have better ideas but you could make use of the current feature engineer functionalities to achieve what you want. See the [vignette on feature engineering](https://ohdsi.github.io/PatientLevelPrediction/articles/AddingCustomFeatureEngineering.html) for an example on how to implement it. 

The vignette is missing couple of steps for what you describe you want to achieve (I thought this was fixed but will review it again).
1) To manipulate the test set an example to get you started is the `univariateFeatureExtraction()` [function](https://github.com/OHDSI/PatientLevelPrediction/blob/fe2e747017783ad450e4f95bf835c826106b2f54/R/FeatureEngineering.R#L102). 
2) Make sure you provide appropriate attributes to the output of your function, as in these [lines ](https://github.com/OHDSI/PatientLevelPrediction/blob/fe2e747017783ad450e4f95bf835c826106b2f54/R/FeatureEngineering.R#L146-L157)

**Comment by andtsouch** [comment]
Thank you for the response, that is a great suggestion since I can see that the custom featureEngineering function is applied both to the trainData and the testData. I will use that to implement the imputation.

**Comment by egillax** [comment]
hi @andtsouch, 

Did you ever implement multiple imputation (or any kind of imputation) that works with the PLP ?  This is something I want to implement in the package.

Cheers,
Egill
