### ISSUE TITLE
checkPlpInstallation url not working

### ISSUE THREAD

**Issue by lcpinheiro** [OHDSI/PatientLevelPrediction#363]
Running `devtools::source_url('https://raw.github.com/OHDSI/PatientLevelPrediction/issue242/extras/checkPlpInstallation.R')` as per the Testing installation instructions for the PLP package (https://ohdsi.github.io/PatientLevelPrediction/articles/InstallationGuide.html) throws a Not Found (HTTP 404) error.

**Comment by jreps** [comment]
not sure why I referenced issue242, need to change the document but the real link should reference main:

devtools::source_url('https://raw.github.com/OHDSI/PatientLevelPrediction/main/extras/checkPlpInstallation.R')

**Comment by jreps** [comment]
This is an easy first commit if somebody wants to fix the link in the documents

**Comment by egillax** [comment]
This has been fixed.
