### ISSUE TITLE
Released version currently failing unit tests

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#406]
https://github.com/OHDSI/PatientLevelPrediction/actions/runs/5770541557/job/15643680529

I see:

```
  Running ‘testthat.R’ [13m/15m]
 [13m/15m] ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
   10.       │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
   11.       │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
   12.       └─PatientLevelPrediction::evaluatePlp(...)
   13.         └─PatientLevelPrediction:::getEvaluationStatistics(...)
   14.           ├─base::do.call(...)
   15.           └─PatientLevelPrediction:::getEvaluationStatistics_binary(...)
   16.             └─PatientLevelPrediction::calibrationLine(...)
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  Error in if (is.null(x[["trace"]]) || trace_length(x[["trace"]]) == 0L) { : 
    missing value where TRUE/FALSE needed
  Calls: test_check ... vapply -> FUN -> paste0 -> format -> format.expectation
  In addition: Warning message:
  call dbDisconnect() when finished working with a connection 
  Execution halted
```

**Comment by egillax** [comment]
This failed again over the weekend but with a better error message: 

https://github.com/OHDSI/PatientLevelPrediction/actions/runs/5911247612/job/16033602072

I think this is because newest [version](https://rstudio.github.io/reticulate/news/index.html) of reticulate changed how indexing works on python objects:

>New [ and [<- methods that invoke Python __getitem__, __setitem__ and __delitem__. The R generics [ and [<- now accept python-style slice syntax like x[1:2:3]. See examples in [?py_get_item](https://rstudio.github.io/reticulate/reference/py_get_item.html).


I'll fix it this week.
