### ISSUE TITLE
Remove reference to ohdsi/ParallelLogger from Remotes in DESCRIPTION

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#411]
Currently the DESCRIPTION file references ohdsi/ParallelLogger in the Remotes section (see [here](
https://github.com/OHDSI/PatientLevelPrediction/blob/86930edfdaf38fd11960435427ffc95081dd192a/DESCRIPTION#L78)).

But ParallelLogger is in CRAN, so this can lead to imaginary version conflicts when a user already has ParallelLogger installed.

Could you remove this reference?

(The same is actually true for IterativeHardThresholding)

**Comment by egillax** [comment]
Fixed in v6.3.7
