### ISSUE TITLE
Use object references when plotting learning curves

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/PatientLevelPrediction#417]
In the learning curve plotting function we refer to objects using string literals in multiple places. This is not good practice and we should instead use object references.

https://github.com/OHDSI/PatientLevelPrediction/blob/7a55c31de7e9a49290c3c35e172962440c70b8a8/R/LearningCurve.R#L366

**Comment by egillax** [comment]
Fixed in v6.3.7
