### ISSUE TITLE
Could you include me for contributor in this repository?

### ISSUE THREAD

**Issue by chandryou** [OHDSI/PatientLevelPrediction#42]
Could you include me for contributor in this repository?
The CIReNN, which I showed you in European OHDSI, is almost completed to integrate with PLP package, thank to Xiaoyong's help. 

I forked this repository, but the forked package can't be installed in my MacBook (I think there is some dependencies. I fetched the original package, but the problem wasn't solved.)
So I want to make a branch in this package to commit my job.

**Comment by schuemie** [comment]
Done! You should now be able to create branches. Note that you cannot push changes to the master branch, you will need to coordinate that with @jreps and @PRijnbeek

**Comment by chandryou** [comment]
Thank you!

**Comment by chandryou** [comment]
@schuemie 
Sorry, but I cannot push anything after making a new branch and checkout to the branch. 
Could you check this again??

**Comment by schuemie** [comment]
Oops, sorry. Can you try again?

**Comment by chandryou** [comment]
Thank you! It works!!
