### ISSUE TITLE
RNN model for PLP package is available now.

### ISSUE THREAD

**Issue by chandryou** [OHDSI/PatientLevelPrediction#43]
Thank  to help from @PRijnbeek , @xypan1232 , the RNN model for PLP package is now available in CIReNN branch.

This packages is based on keas in R. It requires tensorflow and keras package in python and R. You can see the manual how to install R keras [here](https://keras.rstudio.com/). The CIReNN package works based on temporal features now.

I'll upload the demo code for predicting overall mortality in the elderly, which was presented in OHDSI symposium ([poster](http://www.ohdsi.org/web/wiki/lib/exe/fetch.php?media=symposium_2017:ohdsi_cirenn_poster_2017_.pdf) ) 

And I'll add a function for limiting number of covariates for temporal features.

**Comment by xypan1232** [comment]
It is a great job!

**Comment by jreps** [comment]
Hi, I made some edits to completely integrate this into the framework but had to make some edits to get it to run for big data (I see you were also making edits for this at the same time).  The master has now been updated with the modified version, but we might want to edit it to the big data solution you use as that enables the early stopping (or we can manually do that).  The only file that will need to be modified is the CIReNN one as the others files have been updated for keras and temporal data.

**Comment by chandryou** [comment]
Thank you @jreps ! I'm so excited!
I cannot believe that you understand my code perfectly (It wasn't easy to read, because my code is not so good...). Did you make DeepNN by yourself?

By the way, I'm sorry but I couldn't understand what you mean ' we might want to edit it to the big data solution you use as that enables the early stopping (or we can manually do that). The only file that will need to be modified is the CIReNN one as the others files have been updated for keras and temporal data.' and how you would do this.
Could you explain about this further? Sorry for bothering you.

**Comment by chandryou** [comment]
And I'll complete the demo code for CIReNN soon! (maybe this weekend)

**Comment by chandryou** [comment]
@jreps ,
I think prediction of CIReNN module in PLP package always resulted in '1' (non-zero, AUC is always 0.5).
Do you know why this happen?

**Comment by chandryou** [comment]
It works now. Thank you, @jreps
