### ISSUE TITLE
do.call() evaluates plpData parameter to print all its content

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/PatientLevelPrediction#432]
**Describe the bug**
do.call() default behaviour seems to evaluate all objects in its parameter list. For plpData objects this results in an implicit print() action which for very large data (9+mio rows) causes slow down or crashes.

We will experiment using quote() which should defer evaluation until reaching function body.

**Comment by egillax** [comment]
Fixed in v6.3.7
