### ISSUE TITLE
Benchmark Tasks - results and data missing

### ISSUE THREAD

**Issue by ddofer** [OHDSI/PatientLevelPrediction#440]
The current Benchmark Tasks lack any results, dataset details and most importantly results. If they're all empty, page should be renamed "example tasks" at least. 
https://ohdsi.github.io/PatientLevelPrediction/articles/BenchmarkTasks.html

**Comment by egillax** [comment]
I'm sorry the benchmarking tasks are still a work in progress and we should label them as such. Was there anything specific you were looking for?

**Comment by egillax** [comment]
Closing. Feel free to reach out again if you have more more specific requests.
