### ISSUE TITLE
Is there a way to use the exact measurement values in PLP?

### ISSUE THREAD

**Issue by arani11** [OHDSI/PatientLevelPrediction#459]
We used the PLP package to develop a model and weight came out as the top predictor. However, our understanding is that in the PLP this is used as a binary variable (yes/ no) for whether weight was recorded or not. We are interested in using weight as a continuous variable for our prediction model using the PLP package and wondered if there was a way to do this?

**Comment by egillax** [comment]
There will be more imputation methods added to 6.4. Tracked with #461. Closing this issue in favour of that one.

**Comment by arani11** [comment]
Thanks!

________________________________
