### ISSUE TITLE
explicit split settings

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#487]
At the moment we can split the data into train/test and folds by patientId, rowId or time.

It would be nice to have an explicit splitter where you can provide the rowIds for the test/train/folds.  That way you can ensure the same split even with different features etc.

**Comment by egillax** [comment]
Does the proposed code also allow for controlling the training folds ? Like if you need to ensure exactly the same split not only into train/test but as well each fold in train.

**Comment by egillax** [comment]
I added a suggested feature for this in #504

**Comment by egillax** [comment]
Fixed with #504
