### ISSUE TITLE
issue with shiny app

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#489]
When I try and view models in the shiny app it fails due to:

databaseSettings$databaseTable = 'database_meta_table'

but the table name should be 

databaseSettings$databaseTable = 'database_meta_data'

**Comment by jreps** [comment]
I added a pull request to fix this - seems to have been an issue for a while which is odd

**Comment by egillax** [comment]
@jreps I'm assuming you meant to assign me to review the PR not assign me the issue. I reviewed and approved the PR.

**Comment by egillax** [comment]
Fixed by #490
