### ISSUE TITLE
Broken links on readme

### ISSUE THREAD

**Issue by eroell** [OHDSI/PatientLevelPrediction#496]
Hi,

there seem to be some broken links on the readme, namely for the vignettes for [Implementing Existing Patient-Level Predictive Models](https://github.com/OHDSI/PatientLevelPrediction/blob/main/inst/doc/ImplementingExistingModels.pdf) and [Adding Custom Machine Learning Algorithms](https://github.com/OHDSI/PatientLevelPrediction/blob/main/inst/doc/AddingCustomAlgorithms.pdf)

best regards!

**Comment by egillax** [comment]
Thanks @eroell for the report. I will fix those. These files seem to have been removed a while a ago. I'm also going to add a CI check for broken links to stop this from happening again

**Comment by egillax** [comment]
This has now been fixed on latest develop. Install with:

```R
remotes::install_github("OHDSI/PatientLevelPrediction@develop")
```

Have as well added a CI job to check for broken links that runs every time the website is generated.
