### ISSUE TITLE
Broken links for cohorts in the BuildingPredictiveModels document

### ISSUE THREAD

**Issue by eroell** [OHDSI/PatientLevelPrediction#497]
Hey there!

Seems the links to the cohorts in the [Building patient-level predictive models vignette](https://github.com/OHDSI/PatientLevelPrediction/blob/main/inst/doc/BuildingPredictiveModels.pdf) on p.9 are broken... :) Tried on https://atlas-demo.ohdsi.org/#/home to look for these ids, but there they seem to not be present either

**Comment by egillax** [comment]
I need to check where these cohorts are. And find a future solution to point to them. I think the issue with the atlas-demo is that anyone could remove the cohorts.

**Comment by egillax** [comment]
This has now been fixed on latest develop. Install with:
```R
remotes::install_github("OHDSI/PatientLevelPrediction@develop")
```

Have as well added a CI job to check for broken links that runs every time the website is generated.

**Comment by egillax** [comment]
No we don't have a fixed release schedule. There are two things I'm currently working on that I want to finish before the next release. Could be as early as next week or in a few weeks max. Should be soon since last release was in August.

**Comment by eroell** [comment]
Alrighty just been wondering, thanks!
