### ISSUE TITLE
Vignette SQL bug

### ISSUE THREAD

**Issue by eroell** [OHDSI/PatientLevelPrediction#498]
**Describe the bug**
In the vignette [BuildingPrectiveModels.pdf](https://github.com/OHDSI/PatientLevelPrediction/blob/main/inst/doc/BuildingPredictiveModels.pdf) p.9ff

I think in the SQL code

```sql
IF OBJECT_ID('@resultsDatabaseSchema.PLPAFibStrokeCohort', 'U') IS NOT NULL DROP TABLE @resultsDatabaseSchema.PLPAFibStrokeCohort;
CREATE TABLE @resultsDatabaseSchema.PLPAFibStrokeCohort (
cohort_definition_id INT,
subject_id BIGINT,
cohort_start_date DATE,
cohort_end_date DATE
);
```

should read 

```sql
IF OBJECT_ID('@resultsDatabaseSchema.AFibStrokeCohort', 'U') IS NOT NULL DROP TABLE @resultsDatabaseSchema.AFibStrokeCohort;
CREATE TABLE @resultsDatabaseSchema.AFibStrokeCohort (
cohort_definition_id INT,
subject_id BIGINT,
cohort_start_date DATE,
cohort_end_date DATE
);
```

I'm not really sure how the used database emerges and if there's been other things done there, but generally I suppose the later use of `@resultsDatabaseSchema.AFibStrokeCohort` makes only sense with the second snippet above

On a sidenote, sqlite I believe struggles with this parametrization, as to my (not yet that solid) knowledge it doesnt allow multiple schemas straight away... But I guess you're suggestion to use postgres anyways in this example :)

**Comment by egillax** [comment]
Thanks @eroell , this will be fixed. I'm as well having a look over the whole article to make sure it's up to date. I as well want to make it more self-contained since currently it requires a CDM database.

>On a sidenote, sqlite I believe struggles with this parametrization, as to my (not yet that solid) knowledge it doesnt allow multiple schemas straight away... But I guess you're suggestion to use postgres anyways in this example :)

This example should work with all OHDSI supported databases. Which are listed [here](https://ohdsi.github.io/Hades/supportedPlatforms.html) . But yes in case of `sqlite` you'd specify the `resultsDatabaseSchema` and 'cdmDatabaseSchema` as `main`, which is the default `sqlite` schema. 

Btw if you'd want to use `Eunomia` as an example, which uses `sqlite` you'd do something like:

```R
connectionDetails <- Eunomia::getEunomiaConnectionDetails()
Eunomia::createCohorts(connectionDetails)
targetId <- 4 # users of NSAIDs
outcomeId <- 3 # GIbleed

databaseDetails <- createDatabaseDetails(
  connectionDetails = connectionDetails, 
  cdmDatabaseSchema = "main", 
  cdmDatabaseName = "Eunomia",
  cohortDatabaseSchema = "main", 
  cohortTable = "cohort", 
  outcomeDatabaseSchema = "main", 
  outcomeTable =  "cohort",
  targetId = targetId, 
  outcomeIds = outcomeId,
  cdmVersion = 5)

# see ?createCovariateSettings for more options
covariateSettings <- FeatureExtraction::createCovariateSettings(
  useDemographicsAge = TRUE,
  useDemographicsGender = TRUE,
  useConditionOccurrenceAnyTimePrior = TRUE
)

plpData <- getPlpData(databaseDetails = databaseDetails,
                      covariateSettings = covariateSettings,
                      restrictPlpDataSettings = createRestrictPlpDataSettings()) 


populationSettings <- createStudyPopulationSettings(binary = TRUE,
                                                    riskWindowStart = 1,
                                                    riskWindowEnd = 365,
                                                    requireTimeAtRisk = FALSE)

# other models available see: https://ohdsi.github.io/PatientLevelPrediction/reference/index.html#binary-classification-models
modelSettings <- setLassoLogisticRegression(seed = 42)

# where to save model
saveLoc <- "./results/demo/"
plpResult <- runPlp(
  plpData = plpData, 
  outcomeId = outcomeId, 
  analysisId = 'Demo', 
  analysisName = 'Testing analysis',
  populationSettings = populationSettings, 
  splitSettings = createDefaultSplitSetting(splitSeed = 12),
  preprocessSettings = createPreprocessSettings(), 
  modelSettings = modelSettings, 
  logSettings = createLogSettings(verbosity = 'ERROR'),
  executeSettings = createExecuteSettings(
    runSplitData = TRUE,
    runSampleData = FALSE,
    runfeatureEngineering = FALSE,
    runPreprocessData = TRUE,
    runModelDevelopment = TRUE,
    runCovariateSummary = FALSE
  ), 
  saveDirectory = saveLoc
)
````

I will probably add the above as a quick start to the website. Please let me know if there's anything that's not clear. There's also a test database available using `duckdb` [here](https://drive.google.com/file/d/1l5wq57fAslnoFR2umFQvVZbDiq5IK0UF/view?usp=sharing) with 1 million patients generated using [Synthea](https://github.com/synthetichealth/synthea). 

Cheers,
Egill

**Comment by eroell** [comment]
Thanks so much for this self-contained example! This does help understanding what vanilla steps can be involved to run this from start to end.

> This example should work with all OHDSI supported databases. Which are listed [here](https://ohdsi.github.io/Hades/supportedPlatforms.html) . But yes in case of sqlite you'd specify the resultsDatabaseSchema and cdmDatabaseSchema as main

Yes, I think you're right here indeed

**Comment by egillax** [comment]
This has now been fixed on latest develop. Install with:
```R
remotes::install_github("OHDSI/PatientLevelPrediction@develop")
```
