### ISSUE TITLE
Add a covariate builder using cohort_attribute 

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#5]
CDM v5 has a cohort_attribute table. This could be used to populate custom covariates, but we need a new coviate builder to import them into the PLP package.

**Comment by anthonysena** [comment]
Martijn, @fdefalco and I were talking about something similar related to the exclusionConceptIds for CohortMethod. One thought we had was to construct a concept set using Atlas and then retrieve the concept IDs using a call from R to the WebAPI. Not sure if this accomplishes the same goal that you have in mind. What would you think of this approach?

**Comment by schuemie** [comment]
Hi Anthony. I think you're referring to a different problem, one we also need to solve.

I was specifically interested in custom covariates. For example, suppose for a study we needed a covariate of the number of different antidiabetic drugs a person has taken in the last year. This covariate can be included by writing some SQL that populates for each person in the cohort the correct value in the `cohort_attribute` table (this table is at the patient level).

What I think you're bringing up is the need to have some cohort metadata, such as the concept IDs that would be needed to exclude when building covariates for the cohort. This information could reside in the `cohort_definition` table, although currently that table doesn't support a structured way to store that information.

By the way, just as with the cohort table, I imagine people will be creating study-specific instances of tables that have the same structure as `cohort_definition` and `cohort_attribute`.

**Comment by anthonysena** [comment]
Thanks Martijn - yes, my original note was addressing a different problem. As it turns out, the problem and approach you described came up today during one of our studies so the timing is very good. @ericaVoss I think this is exactly what we were discussing internally today as it relates to CohortMethod.

**Comment by cgreich** [comment]
Friends:

If you have good ideas how to structure this please consider submitting: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:next_cdm.

**Comment by schuemie** [comment]
This feature is added [here](cfd180ef1bebd968d607356916121c8433c22254). See new vignette for how to use.

**Comment by cgreich** [comment]
Dead link, Martijn

**Comment by schuemie** [comment]
Fixed link
