### ISSUE TITLE
small bug in predictCyclopsType

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#507]
in predictCyclopsType() there is the line:

intercept <- coefficients$betas[coefficients$covariateId%in%'(Intercept)']

I believe there is a missing 's' and this should be 

intercept <- coefficients$betas[coefficients$covariateId**s**%in%'(Intercept)']

I think this will not cause issues because R lets you be lazy with the names but we should fix this anyway in case things change.

**Comment by egillax** [comment]
Thanks! This stuff worried me when I saw your issue. But as you say R does some magic and still gets the intercept. I've made a PR to fix this and will merge once green.

**Comment by egillax** [comment]
Fixed with #508
