### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by pavgra** [OHDSI/PatientLevelPrediction#54]
Would be great to be able to pass number of threads to `fitGLMModel` or, at least, to log number of threads which was automatically picked

**Comment by jreps** [comment]
At the moment we use threads=-1 (which I think should use all the threads available).  I can update the code to have threads as a parameter in setLassoLogisticRegression with a default of -1 as this will enable you to pass a different value and will also log the number of threads used.  I'll add this in the next PLP update, thanks for the suggestion.

**Comment by jreps** [comment]
added
