### ISSUE TITLE
`writeLines` vs Condition Handling

### ISSUE THREAD

**Issue by mustafaascha** [OHDSI/PatientLevelPrediction#57]
I notice that `writeLines` is used in place of [`message`, `error`, and `warning`](https://adv-r.hadley.nz/conditions.html). 

It appears that most of this output is more along the lines of a `message`, but there are a few cases (database connectivity in `R/HelperFunctions.R`, for example) where it might be helpful to signal an error. 

If it's not essential, I'm happy to swap out some of the `writeLines` with the signal that seems most appropriate for the condition.

**Comment by jreps** [comment]
Hi, the writeLines were the old logging style we first used when the package was written but we now use functions written by Martijn in OhdsiRTools such as OhdsiRTools::logInfo, so updating the writeLines with the proper logging function would be great.  The document for the logging is: https://raw.githubusercontent.com/OHDSI/OhdsiRTools/master/inst/doc/Logging.pdf

**Comment by schuemie** [comment]
I wanted to test it some more myself before implementing it elsewhere, but just so you know that the logging and parallel execution functionality has been moved from OhdsiRTools to [ParallelLogger](https://cran.r-project.org/web/packages/ParallelLogger/index.html). The reason being that OhdsiRTools is too much of a ragtag of function, and wasn't allowed in CRAN. 

The functions are still also in OhdsiRTools, but will be deprecated in the future.

**Comment by mustafaascha** [comment]
@schuemie - That's interesting--are the ParallelLogger functions `logWarn`, `logInfo`, and `logFatal` the preferred equivalents of base R's `warning`, `message`, and `error`? Or is it better to stick with the base conditions because they're still logged by ParallelLogger? 

@jreps Depending on the answer to the above, for sure I'll swap log functions to meet new style.

**Comment by schuemie** [comment]
Unfortunately, I could not find a way to capture `message`. So I prefer `warning` and `stop` over `logWarn` and `logFatal`, because the former imply the latter. But I prefer `logInfo` over `message`, because the latter does not imply the former.
