### ISSUE TITLE
Dependency ReporteRs has been removed from CRAN

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PatientLevelPrediction#58]
This makes installing PLP a bit difficult: https://cran.r-project.org/web/packages/ReporteRs/index.html

**Comment by jreps** [comment]
Good spot, I see this package: https://cran.r-project.org/web/packages/officer/officer.pdf has replaced it, so I'll update the code using that.

**Comment by jreps** [comment]
Updated code to remove ReporteRs
