### ISSUE TITLE
Support multitask modeling

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#64]
If plpData has multiple outcomes - can we add ability to predict all outcomes at the same time in the neural network models.  Will require modifying performance metrics.

**Comment by xypan1232** [comment]
in this preprint https://arxiv.org/pdf/1808.03331.pdf, it says multi-task learning underperform than single-task in most cases

**Comment by jreps** [comment]
It might have value for rare conditions, but then we will need to know associated illnesses, so given that paper it probably isn't worth investing time in for now.  I'll close this.
