### ISSUE TITLE
loadPlpModel shold be changed because the model is saved under dir plpResult/model now?

### ISSUE THREAD

**Issue by xypan1232** [OHDSI/PatientLevelPrediction#65]
when I used loadPlpModel to load the models, it says that the model files do not exist. I checked it and find now the models is saved under plpResult/model

**Comment by jreps** [comment]
If you use savePlpModel() it will save it to any directory you want, if you use savePlpResult() then it saves the model in the plpResult folder in the directory you want to save the results.

In runPlp there is an option to save the plpResult, I think that is saving the result.  If you want to save just the model then you can run savePlpModel() with the model and saving directory as inputs.
