### ISSUE TITLE
Need to update the vignettes

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#7]
When I redo all the steps in the current vignettes I run into the following issues:
1. RenderSQL now needs resultsDatabaseSchema defined to run.
2. The hospitalisation example is not running anymore because the datediff function is rendered to a to_date difference which does not work if the field is of type Date already. I think it should simply be, e.g, (visit_start_date - observation_period_start_date) > 365

I am running PostgreSQL on the latest CDM version using the latest SQLRender.

@schuemie if you agree I can make the change.

**Comment by chrisknoll** [comment]
This article has a pretty good example of converting TSQL into Postgresql datediff functions:
http://www.sqlines.com/postgresql/how-to/datediff

Specifically for finding difference in days:

~~~~sql
  -- Difference between Dec 29, 2011 23:00 and Dec 31, 2011 01:00 in days
  SELECT DATEDIFF(day, '2011-12-29 23:00:00', '2011-12-31 01:00:00');
  -- Result: 2
~~~

becomes:

~~~sql
  -- Difference between Dec 29, 2011 23:00 and Dec 31, 2011 01:00 in days
  SELECT DATE_PART('day', '2011-12-31 01:00:00'::timestamp - '2011-12-29 23:00:00'::timestamp);
  -- Result: 1
~~~
notice the semantic diff (2 vs. 1) but shoudlnt matter for us since we round to nearest day.

**Comment by schuemie** [comment]
Hi Peter,

I just fixed the schema name in the vignette. But I'm not sure what you mean by "datediff function is rendered to a to_date difference which does not work if the field is of type Date already." This is the procedure we use everywhere, including Achilles, which runs fine on Postgres. Also, the only way to fix it is to change the translation behavior of SqlRender, which will probably break a lot of other things. Could you tell me what the specific error message is that you see?

**Comment by PRijnbeek** [comment]
Thanks.

I found what went wrong. I run sql <- translateSql(sql, targetDialect = connectionDetails$dbms)$sql twice by mistake and for some reason this gives this sql back:


CREATE TABLE  results.rehospitalization  AS

SELECT

 visit_occurrence.person_id AS subject_id,

  MIN(visit_start_date) AS cohort_start_date,

  ( MIN(visit_start_date) +  30) AS cohort_end_date, 1 AS cohort_definition_id


FROM

 cdm.visit_occurrence

INNER JOIN cdm.observation_period

  ON visit_occurrence.person_id = observation_period.person_id INNER JOIN cdm.condition_occurrence

  ON condition_occurrence.person_id = visit_occurrence.person_id

WHERE visit_concept_id IN (9201, 9203)

  AND (TO_DATE( visit_start_date , 'YYYYMMDD') - TO_DATE( observation_period_start_date , 'YYYYMMDD')) > 365 AND visit_start_date > observation_period_start_date

  AND (TO_DATE( observation_period_end_date , 'yyyymmdd') - TO_DATE( visit_start_date , 'yyyymmdd')) > 30 AND visit_start_date < observation_period_end_date

  AND (TO_DATE( visit_start_date , 'yyyymmdd') - TO_DATE( condition_start_date , 'yyyymmdd')) > 365 AND condition_start_date <= visit_start_date

  AND condition_concept_id IN (

    SELECT descendant_concept_id

    FROM cdm.concept_ancestor

    WHERE ancestor_concept_id = 201826) /* Type 2 DM */

GROUP BY visit_occurrence.person_id;


When I run this I got the message:


ERROR:  function to_date(date, unknown) does not exist

LINE 13:   AND (TO_DATE( visit_start_date , 'YYYYMMDD') - TO_DATE( ob...

                ^

HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

Query failed

PostgreSQL said: function to_date(date, unknown) does not exist

Hint: No function matches the given name and argument types. You might need to add explicit type casts.


This is because no TO_DATE exists with date as date type.


I do not understand why it translates it to this code though might be good to check still?
