### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#71]
**CreatingNetworkStudies.pdf** 

- [x] We need to completely rewrite or remove this vignette since the package skeleton has changed and we will have the new Atlas functionality

**AddingExistingModels.pdf**

- [x] Need to fix typos, pdf rendering, and explanation at certain points

**BuildingMultiplePredictionModel.pdf**

- [x] Rename to BuildingMultiplePredictiveModels.pdf
- [x] We need add text about the functionality that it will continue if it stops at some point and you call it again. 
- [x] Fix typos

**BuildingPredictiveModels.pdf**
- [x] Need to refer to the installationGuide.pdf
- [x] We need to test the examples are still functional
- [x] Fix typos
- [x] We should make clear that runPLP will only work for one outcome cohort not the outcome cohorts extracted by getPlP
- [x] Need to add the deepLearning models (refer to that vignette)
- [x] Add the ensemble methods (refer to that vignette)
- [x] Refer to learningCurve funtionality
- [x] Add screenshot of ShinyApp in a separate paragraph
- [x] Add the new calibration plot + image
- [x] Add Jamia paper reference
- [x] Add the functionality to create the Word Document

**EnsembleTraining.pdf**
- [x] Text needs to be optimised (typos, unclear sentences)

**InstallationGuide.pdf**
- [x] We need to make clear what the difference is between installing with drat (last release) and the devtools approach (bleeding edge)
- [x] Fix pdf render errors (for example section 5)
- [x] Section 7 should be moved to the other section (which also installs deep learning libraries)
- [x] Fix typos

**PlottingLearningCurves.pdf**
- [x] Change to GeneratingLearningCurves.pdf
- [x] Change author order (Henrik is first author) + add date
- [x] Minor text improvements

**CustomPredictionModels.pdf**
- [x] section 2.2 pdf rendering is not correct
- [x] There is a ToDo in the fit function example (Jenna)
- [x] Fix typos
- [x] Have someone test the code that did not add a new algorithm before.

**Comment by lhjohn** [comment]
BuildingMultiplePredictionModel.pdf - In Section 6, third code snippet: the function `runPlpAnalyses()` has a parameter `cdmDatabaseName`, which should be mentioned in that code snippet, because it has no default value.

**Comment by PRijnbeek** [comment]
Alle vignettes are updated and final in document branch ready to go once final check from Jenna is done (see above check list).

**Comment by jreps** [comment]
I was looking at the vignette folder and noticed we have some redundancies:

The rmd files we have are:
- PlottingLearningCurves.Rmd – 9 months ago
- GeneratingLearningCurves.Rmd – 5 months ago
- ImplementingExistingModels.Rmd – 5 months ago
- AddingExistingModels.Rmd – 5 months ago
- AddingCustomAlgorithms.Rmd – 5 months ago
- CustomPredictionAlgorithms.Rmd – 10 months ago
- InstallationGuide.Rmd  - 5 months ago (need to update for new reticulate but need to check installation)
- CreatingNetworkStudies.Rmd – 10 months ago
- BuildingPredictiveModels.Rmd – 5 months ago
- BuildingMultiplePredictiveModels – 5 months ago
- BuildingEnsembleModels.Rmd – 5 months ago
- BuildingDeepLearningModels.Rmd – 5 months ago

Can we delete PlottingLearningCurves.Rmd, CustomPredictionAlgorithms.Rmd and either ImplementingExistingModels.Rmd or AddingExistingModels.Rmd as I think these are duplicates?

**Comment by lhjohn** [comment]
PlottingLearningCurves.Rmd is an old version and can be removed.

**Comment by PRijnbeek** [comment]
See the Readme.Rmd these we should keep. Implementing keep. AddingExistingModels delete. CustomPredictionAlgorithms delete.

**Comment by jreps** [comment]
Thanks, I've removed the old ones.  We just need to update the network study or maybe remove it and refer people to the demo videos?  The website https://ohdsi.github.io/PatientLevelPrediction/ now has a video button with some of the videos added. I added updated installation information to https://ohdsi.github.io/PatientLevelPrediction/articles/PatientLevelPrediction.html - anyone who has python set up for pythonInR shouldn't have to do anything as reticulate will use the same settings, but for new users of the package the install instructions have changed (hopefully making it easier) and there is an option of using a virtual python environment

**Comment by jreps** [comment]
I think we need to update the package install document - it is a lot easier to install now as we use reticulate and I have a function that will set up a conda environment with all the dependancies

Might need to check all documentation and update based on recent edits - we are moving over to Anaconda from ff and that will mean editing the documents

**Comment by jreps** [comment]
documentation has been updated
