### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#73]
- [x] Add all the new vignettes
- [ ] We need an updated demo video (record during next PlP TC?)

**Comment by PRijnbeek** [comment]
Done in the documentation branch. Have  a look @jreps 

The links to the vignettes will work once they are in master, but we need to double check.

See also these issues to be decided on:

#93 and #92 

Peyer

**Comment by jreps** [comment]
Can we use our videos (that will soon be on youtube) as the updated demo video?

**Comment by jreps** [comment]
We now have videos in the website: https://ohdsi.github.io/PatientLevelPrediction/ so I'm closing this
