### ISSUE TITLE
Add loop of interpretInstallCode(N)

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#76]
It would be nice if we add a loop after checkPlpInstallation that runs
PatientLevelPrediction::interpretInstallCode(N) for each code so the user does not have to do this manually or will send us just the number and then we have to run it.

Needs change in Installation guide once added.

**Comment by jreps** [comment]
I'm a bit confused.  checkPlpInstallation() should just return a single number, that can then be input into PatientLevelPrediction::interpretInstallCode() once to figure out what is wrong.  Cohort method had a check that returned a number that people had to run before a tutorial to make sure everything was set up correctly, so for consistency PLP had the same.  To get the text responses when running checkPlpInstallation()  just add PatientLevelPrediction::interpretInstallCode(current return of checkPlpInstallation()) to the final line of checkPlpInstallation().

**Comment by PRijnbeek** [comment]
If it is just one number we best just call the InterpretInstallCode in that function we indeed do not need a loop, i was thinking it is returning a list (multiple errors could occur right?). No need to share an uninformative number.
