### ISSUE TITLE
Shiny app indices of viewMultiplePlp() are not consistent with analysis ids

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/PatientLevelPrediction#77]
The indices of the first column are a bit misleading as they do not represent analysis ids.

![indices](https://user-images.githubusercontent.com/7384198/45171203-0e09c480-b202-11e8-8e31-ee8fa2da053e.PNG)

**Comment by jreps** [comment]
I think this is due to the row names (which are just the row numbers when the row names of the data.frame are NULL) being automatically added with the shiny interactive table

**Comment by PRijnbeek** [comment]
Yes indeed, maybe we can hide the Index column. I would also be nice to have separate column with the analysis id since this refers to the folder you have to got to.
