### ISSUE TITLE
Vertical axis range of precision-recall plot and F1 score plot should not be scaled dynamically

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/PatientLevelPrediction#79]
Both vertical axes should have a static range from 0 to 1 in the viewMultiplePlp() Shiny app.

![axes](https://user-images.githubusercontent.com/7384198/45171902-f29fb900-b203-11e8-9a44-a9e08aab3123.PNG)

**Comment by jreps** [comment]
The shiny app just use the standard plp plots, so if this is to be changed it needs to be edited in these plots.

**Comment by PRijnbeek** [comment]
Yes, maybe we can make an option in these plotfunctions to auto scale or not. In the Shiny App it would be best if we have the same scale across the analysis or maybe in the future we could make the plots in the shiny app more fancy to autoscale on the fly. Not a priority now but a nice to have.

**Comment by egillax** [comment]
After discussing with @lhjohn . Closing. Most people nowadays use the shiny to view results.
