### ISSUE TITLE
Generated PLP R code by Atlas

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#86]
I am doing some tests in the Amazon Vm. I created use the T2DM cohort and created a HF cohort on Synpuf 2.3 (not bad as an example and results are ok....) and I have some questions/suggestions: 

- [ ] Form settings

I noticed that for Procedures and Measurements we do not have All time prior which we have for Conditions and Drugs. Any reason for this?  

- [ ] Package installation text

The generated code has this: 

```
# Uncomment to install PatientLevelPrediction
# install.packages("devtools")# library("devtools")
# devtools::install_github("ohdsi/PatientLevelPrediction", ref = "2.0.0") 
```

Are we indeed asking them to install a version through devtools or via drat? We need to update this when we have the final version of course but I suppose this is on the final todo list. 

- [ ] Variable names 

```
cohortTable <- "cohort_table"
outcomeTable <- "outcome_table" 
```

If students run the Atlas in the VM what do they have to fill in here? Why do we actually have these names, they are confusing to me. Both the Target and the Outcome are cohorts right? Would targetCohortTable and outcomeCohortTable not be better names considering our paper and tutorial? Can also understand if the OutcomeCohort term is confusing to some but then I would still call the first targetCohortTable and second maybe  OutcomeTable. We need to be consistent with PLE approach though. 

- [ ] User settings in code

Can we make it more clear in the generated R code which parts they need to fill in? The ToDO is only in at the connection Details  but they also need to fill in the schemas etc below but then not change the targetCohortId etc. We may need to make this more dummy proof. 
For example: 
```
###########
# Fill in  your connection details, schemas, and table names: 
< code> 
###########
# Auto generated code based on your settings in Atlas:  
< code> 

```

- [ ] Error is location of results

When I run the code as generated by Atlas a plpmodels folder is created that has an 2018… folder but this folder is also generated at the level of the OutputFolder?

![screenshot 2018-09-21 11 44 03](https://user-images.githubusercontent.com/7252105/45874055-319d4500-bd94-11e8-941a-3d5fea1119ce.png)

- [ ] Textual suggestions for generated R code 

Current text | Suggestion
------------------------------ | -----------------
"If you want to use your code in a distributed network study you will need to create a temporary cohort table with common cohort IDs. etc.." | It is true but I am not sure we should still have this..suggest to remove.
"to interactively view the performance:" | View the model performance in a Shiny App 
"add plots and document to output folder:" | Generate plots containing the performance measures and descriptives And then later add  "Generate a word document containing the study specification and results". I would add after each of these statements where the results are stored, e,g. "Plots are stored in: …." 
Individual Plots section |  I would remove this it is a bit messy. Details are in the vignette.

**Comment by jreps** [comment]
Atlas is currently outdated for plp which is the cause for most/all of the issues. 

In amazon the plp package will be installed, so the package install code should never be run.

I don't understand the database question, is the atlas interface about to run the prediction code without somebody copying and pasting?  Will they only have one database?

The saving is an issue with the outdated atlas interface to plp saving results which isn't needed.

The text will not be there when the interface is updated.

I don't entend to use this during our tutorial unless atlas is updated with the interface.

**Comment by PRijnbeek** [comment]
Atlas is currently outdated for plp which is the cause for most/all of the issues.

> I understand that this is not the latest PLP and Atlas version. However, we do need to make sure these things are corrected in the new version. Better to flag this now than later.

In amazon the plp package will be installed, so the package install code should never be run.
> Yes i understand that it is installed in the VM, but we want the generated code also to be used by people outside our tutorial. Therefore this should be updated with the latest release and we need probably use drat instead or  devtools (unless we need to fix the version to match Atlas)

I don't understand the database question, is the atlas interface about to run the prediction code without somebody copying and pasting? Will they only have one database?

> Not sure which database question you are referring to?

The saving is an issue with the outdated atlas interface to plp saving results which isn't needed
> OK, will test again later

The text will not be there when the interface is updated.
> What text will be there then? can I review that already? I suppose the new version is based on the text you currently have.

I don't entend to use this during our tutorial unless atlas is updated with the interface.
> Not sure what you mean? This should work and be clear since we do a new release, students will be playing with this in the course, and we want all other people to...

**Comment by PRijnbeek** [comment]
Closed for now since we only have hydra R package generated code.
