### ISSUE TITLE
ShinyApp issues

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/PatientLevelPrediction#94]
Can we remove the attrition field in the populationsettings since we now have the attrition tab?

I often see that the demographics tab is not showing results (prop because there is no gender, age covariate etc) is it possible to add a note if that is the case instead of an empty graph?

**Comment by PRijnbeek** [comment]
Found a way to fix this using validate function.  I will fix this

**Comment by jreps** [comment]
Was this resolved?
